// Acorda Portugal â€” Game Data
// Base de dados local/demo do protÃ³tipo.

import type { LucideIcon } from 'lucide-react'
import {
  Flag,
  Landmark,
  Globe,
  Medal,
  Music,
  UtensilsCrossed,
  Clapperboard,
  Lightbulb,
  Laugh,
  FlaskConical,
  Cpu,
  Earth,
  Drama,
} from 'lucide-react'

export type Tone = 'primary' | 'gold' | 'red' | 'accent'

export type Category = {
  name: string
  icon: LucideIcon
  tone: Tone
  description: string
  questions: string
  difficulty: 'FÃ¡cil' | 'MÃ©dio' | 'DifÃ­cil' | 'Variado'
  special?: boolean
}

export const CATEGORIES: Category[] = [
  {
    name: 'Portugal',
    icon: Flag,
    tone: 'primary',
    description: 'Testa o que sabes sobre o paÃ­s.',
    questions: '1.240',
    difficulty: 'Variado',
  },
  {
    name: 'HistÃ³ria',
    icon: Landmark,
    tone: 'gold',
    description: 'Dos Descobrimentos aos dias de hoje.',
    questions: '980',
    difficulty: 'MÃ©dio',
  },
  {
    name: 'Geografia',
    icon: Globe,
    tone: 'primary',
    description: 'Rios, serras, distritos e capitais.',
    questions: '760',
    difficulty: 'MÃ©dio',
  },
  {
    name: 'Desporto',
    icon: Medal,
    tone: 'red',
    description: 'Futebol, olÃ­mpicos e lendas nacionais.',
    questions: '1.050',
    difficulty: 'FÃ¡cil',
  },
  {
    name: 'MÃºsica',
    icon: Music,
    tone: 'accent',
    description: 'Do fado ao pop portuguÃªs.',
    questions: '640',
    difficulty: 'MÃ©dio',
  },
  {
    name: 'Cinema & TV',
    icon: Clapperboard,
    tone: 'accent',
    description: 'Filmes, sÃ©ries e novelas icÃ³nicas.',
    questions: '520',
    difficulty: 'MÃ©dio',
  },
  {
    name: 'Gastronomia',
    icon: UtensilsCrossed,
    tone: 'gold',
    description: 'Pratos, doces e sabores de norte a sul.',
    questions: '480',
    difficulty: 'FÃ¡cil',
  },
  {
    name: 'Cultura',
    icon: Drama,
    tone: 'primary',
    description: 'TradiÃ§Ãµes, arte e patrimÃ³nio.',
    questions: '610',
    difficulty: 'MÃ©dio',
  },
  {
    name: 'CiÃªncia',
    icon: FlaskConical,
    tone: 'accent',
    description: 'Do Ã¡tomo ao universo.',
    questions: '720',
    difficulty: 'DifÃ­cil',
  },
  {
    name: 'Tecnologia',
    icon: Cpu,
    tone: 'primary',
    description: 'Gadgets, cÃ³digo e inovaÃ§Ã£o.',
    questions: '540',
    difficulty: 'MÃ©dio',
  },
  {
    name: 'Mundo',
    icon: Earth,
    tone: 'gold',
    description: 'PaÃ­ses, bandeiras e curiosidades.',
    questions: '890',
    difficulty: 'MÃ©dio',
  },
  {
    name: 'Conhecimentos Gerais',
    icon: Lightbulb,
    tone: 'primary',
    description: 'Um pouco de tudo para todos.',
    questions: '1.480',
    difficulty: 'Variado',
  },
  {
    name: 'Modo Maluco',
    icon: Laugh,
    tone: 'red',
    description: 'Perguntas que nÃ£o fazem sentido. Mas tÃªm resposta.',
    questions: '50',
    difficulty: 'Variado',
    special: true,
  },
]

export type Player = {
  pos: number
  name: string
  district: string
  level: number
  xp: string
}

export const NATIONAL_TOP: Player[] = [
  { pos: 1, name: 'ZÃ©_Mestre', district: 'Porto', level: 47, xp: '182 450' },
  { pos: 2, name: 'AnaQuiz', district: 'Lisboa', level: 44, xp: '176 120' },
  { pos: 3, name: 'TugaBrain', district: 'Braga', level: 42, xp: '168 900' },
  { pos: 4, name: 'MiaSabe', district: 'Aveiro', level: 40, xp: '154 210' },
  { pos: 5, name: 'RuiRelÃ¢mpago', district: 'Coimbra', level: 39, xp: '149 640' },
  { pos: 6, name: 'CarlaGeo', district: 'Faro', level: 38, xp: '141 300' },
  { pos: 7, name: 'PedroPro', district: 'SetÃºbal', level: 37, xp: '138 470' },
  { pos: 8, name: 'InÃªsFado', district: 'Viseu', level: 36, xp: '132 090' },
  { pos: 9, name: 'JoÃ£oFlash', district: 'Leiria', level: 35, xp: '127 800' },
  { pos: 10, name: 'SaraSpeed', district: 'Ã‰vora', level: 34, xp: '121 560' },
]

export type District = {
  pos: number
  name: string
  players: string
  xp: string
}

export const DISTRICTS: District[] = [
  { pos: 1, name: 'Porto', players: '18 420', xp: '2 940 300' },
  { pos: 2, name: 'Lisboa', players: '21 050', xp: '2 880 120' },
  { pos: 3, name: 'Braga', players: '9 640', xp: '1 420 900' },
  { pos: 4, name: 'Aveiro', players: '7 210', xp: '980 400' },
  { pos: 5, name: 'Coimbra', players: '5 980', xp: '742 100' },
  { pos: 6, name: 'SetÃºbal', players: '6 340', xp: '690 550' },
  { pos: 7, name: 'Vila Real', players: '1 248', xp: '182 450' },
]

export type Level = {
  level: number
  title: string
  xp: string
}

export const LEVELS: Level[] = [
  { level: 1, title: 'Curioso', xp: '0' },
  { level: 2, title: 'Aprendiz', xp: '1.000' },
  { level: 3, title: 'Conhecedor', xp: '5.000' },
  { level: 4, title: 'Especialista', xp: '15.000' },
  { level: 5, title: 'Mestre', xp: '40.000' },
]

export type Mission = {
  icon: 'target' | 'flame' | 'brain'
  title: string
  reward: string
  progress: number
  total: number
  gold?: boolean
}

export const MISSIONS: Mission[] = [
  {
    icon: 'target',
    title: 'Responder a 10 perguntas',
    reward: '+100 XP',
    progress: 3,
    total: 10,
  },
  {
    icon: 'flame',
    title: 'Acertar 5 seguidas',
    reward: '+â‚¬50',
    progress: 4,
    total: 5,
    gold: true,
  },
  {
    icon: 'brain',
    title: 'Jogar 3 partidas',
    reward: '+150 XP',
    progress: 1,
    total: 3,
  },
]

export const WEEK_DAYS = [
  { label: 'Seg', done: true },
  { label: 'Ter', done: true },
  { label: 'Qua', done: true },
  { label: 'Qui', done: true },
  { label: 'Sex', done: true },
  { label: 'SÃ¡b', done: true },
  { label: 'Dom', done: true },
]

export type GameEvent = {
  title: string
  tag: string
  tone: Tone
  reward: string
  timeLeft: string
  icon: 'flag' | 'flame' | 'medal' | 'laugh'
}

export const EVENTS: GameEvent[] = [
  {
    title: 'Desafio Nacional',
    tag: 'Ao vivo',
    tone: 'primary',
    reward: '5.000 XP + â‚¬500',
    timeLeft: 'Termina em 2d 14h',
    icon: 'flag',
  },
  {
    title: 'Semana de Portugal',
    tag: 'Especial',
    tone: 'red',
    reward: 'Distintivo exclusivo',
    timeLeft: 'Termina em 5d 03h',
    icon: 'flame',
  },
  {
    title: 'Especial Desporto',
    tag: 'TemÃ¡tico',
    tone: 'gold',
    reward: '+â‚¬250',
    timeLeft: 'Termina em 1d 08h',
    icon: 'medal',
  },
  {
    title: 'Modo Maluco',
    tag: 'Divertido',
    tone: 'accent',
    reward: '2Ã— XP',
    timeLeft: 'Termina em 3d 20h',
    icon: 'laugh',
  },
]

export type Achievement = {
  icon: 'coins' | 'star' | 'trophy' | 'flame' | 'crown'
  title: string
  text: string
  tone: Tone
}

export const ACHIEVEMENTS: Achievement[] = [
  {
    icon: 'coins',
    title: 'Euros virtuais',
    text: 'Moeda do jogo para desbloquear extras.',
    tone: 'gold',
  },
  {
    icon: 'star',
    title: 'XP',
    text: 'Sobe de nÃ­vel a cada resposta certa.',
    tone: 'primary',
  },
  {
    icon: 'trophy',
    title: 'Conquistas',
    text: 'Coleciona distintivos raros.',
    tone: 'gold',
  },
  {
    icon: 'flame',
    title: 'Streak',
    text: 'Joga todos os dias sem falhar.',
    tone: 'red',
  },
  {
    icon: 'crown',
    title: 'Rankings',
    text: 'Chega ao topo nacional e do teu distrito.',
    tone: 'primary',
  },
]

export type QuizQuestion = {
  category: string
  index: number
  total: number
  question: string
  options: {
    key: 'A' | 'B' | 'C' | 'D'
    text: string
  }[]
  correct: 'A' | 'B' | 'C' | 'D'
  explanation: string
  points: number
}

export const MODO_MALUCO_QUESTIONS: QuizQuestion[] = [
  {
    category: 'Modo Maluco',
    index: 1,
    total: 70,
    question: 'Se uma galinha puser um ovo em cima de um muro, para que lado cai o ovo?',
    options: [
      { key: 'A', text: 'Para a esquerda' },
      { key: 'B', text: 'Para a direita' },
      { key: 'C', text: 'Para o lado mais baixo' },
      { key: 'D', text: 'Nenhum: galinhas nÃ£o pÃµem ovos em cima de muros' },
    ],
    correct: 'D',
    explanation: 'A rasteira estÃ¡ na prÃ³pria pergunta: nÃ£o Ã© o cenÃ¡rio normal de uma galinha pÃ´r um ovo num muro.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 2,
    total: 70,
    question: 'O que pesa mais: 1 kg de ferro ou 1 kg de penas?',
    options: [
      { key: 'A', text: 'O ferro' },
      { key: 'B', text: 'As penas' },
      { key: 'C', text: 'Pesam exatamente o mesmo' },
      { key: 'D', text: 'Depende da cor das penas' },
    ],
    correct: 'C',
    explanation: 'Um quilograma Ã© um quilograma, independentemente do material.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 3,
    total: 70,
    question: 'Quantos meses tÃªm 28 dias?',
    options: [
      { key: 'A', text: '1' },
      { key: 'B', text: '2' },
      { key: 'C', text: '11' },
      { key: 'D', text: 'Todos' },
    ],
    correct: 'D',
    explanation: 'Todos os meses tÃªm pelo menos 28 dias.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 4,
    total: 70,
    question: 'Um comboio elÃ©trico vai para norte. Para que lado vai o fumo?',
    options: [
      { key: 'A', text: 'Norte' },
      { key: 'B', text: 'Sul' },
      { key: 'C', text: 'Para onde sopra o vento' },
      { key: 'D', text: 'NÃ£o hÃ¡ fumo' },
    ],
    correct: 'D',
    explanation: 'Ã‰ um comboio elÃ©trico, portanto a pergunta tenta fazer-te imaginar um fumo que nÃ£o existe.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 5,
    total: 70,
    question: 'Tens trÃªs maÃ§Ã£s e tiras duas. Com quantas maÃ§Ã£s ficas?',
    options: [
      { key: 'A', text: 'Uma' },
      { key: 'B', text: 'Duas' },
      { key: 'C', text: 'TrÃªs' },
      { key: 'D', text: 'Nenhuma' },
    ],
    correct: 'B',
    explanation: 'Se tiraste duas maÃ§Ã£s, ficas com as duas que tens contigo.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 6,
    total: 70,
    question: 'O pai da Maria tem cinco filhas: Nana, Nene, Nini, Nono e...?',
    options: [
      { key: 'A', text: 'Nunu' },
      { key: 'B', text: 'Maria' },
      { key: 'C', text: 'Nana outra vez' },
      { key: 'D', text: 'Joana' },
    ],
    correct: 'B',
    explanation: 'A Maria jÃ¡ estÃ¡ escondida na prÃ³pria pergunta.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 7,
    total: 70,
    question: 'Se ultrapassares a pessoa que estÃ¡ em segundo lugar numa corrida, em que posiÃ§Ã£o ficas?',
    options: [
      { key: 'A', text: 'Primeiro' },
      { key: 'B', text: 'Segundo' },
      { key: 'C', text: 'Terceiro' },
      { key: 'D', text: 'Ãšltimo' },
    ],
    correct: 'B',
    explanation: 'Ao ultrapassares o segundo classificado, passas a ocupar o segundo lugar.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 8,
    total: 70,
    question: 'O que tem dentes mas nÃ£o consegue morder?',
    options: [
      { key: 'A', text: 'Um cÃ£o' },
      { key: 'B', text: 'Um pente' },
      { key: 'C', text: 'Um tubarÃ£o' },
      { key: 'D', text: 'Um crocodilo' },
    ],
    correct: 'B',
    explanation: 'Um pente tem dentes, mas nÃ£o tem boca.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 9,
    total: 70,
    question: 'O que fica mais molhado quanto mais seca?',
    options: [
      { key: 'A', text: 'Uma toalha' },
      { key: 'B', text: 'Uma esponja' },
      { key: 'C', text: 'Uma nuvem' },
      { key: 'D', text: 'Um peixe' },
    ],
    correct: 'A',
    explanation: 'A toalha fica molhada enquanto seca outras coisas.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 10,
    total: 70,
    question: 'O que tem pescoÃ§o mas nÃ£o tem cabeÃ§a?',
    options: [
      { key: 'A', text: 'Uma garrafa' },
      { key: 'B', text: 'Um cavalo' },
      { key: 'C', text: 'Uma girafa' },
      { key: 'D', text: 'Um humano' },
    ],
    correct: 'A',
    explanation: 'A garrafa tem um pescoÃ§o ou gargalo, mas nÃ£o tem cabeÃ§a.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 11,
    total: 70,
    question: 'Se disseres o meu nome, deixo de existir. O que sou?',
    options: [
      { key: 'A', text: 'O silÃªncio' },
      { key: 'B', text: 'O ar' },
      { key: 'C', text: 'A sombra' },
      { key: 'D', text: 'A luz' },
    ],
    correct: 'A',
    explanation: 'Quando falas, o silÃªncio deixa de existir.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 12,
    total: 70,
    question: 'Quanto mais tiras, maior fica. O que Ã©?',
    options: [
      { key: 'A', text: 'Um buraco' },
      { key: 'B', text: 'Uma pizza' },
      { key: 'C', text: 'Uma dÃ­vida' },
      { key: 'D', text: 'Uma mochila' },
    ],
    correct: 'A',
    explanation: 'Quanto mais terra tiras, maior fica o buraco.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 13,
    total: 70,
    question: 'Qual Ã© a coisa que estÃ¡ sempre Ã  tua frente mas nunca consegues ver?',
    options: [
      { key: 'A', text: 'O passado' },
      { key: 'B', text: 'O futuro' },
      { key: 'C', text: 'O nariz' },
      { key: 'D', text: 'O cabelo' },
    ],
    correct: 'B',
    explanation: 'O futuro estÃ¡ Ã  nossa frente, mas nÃ£o podemos vÃª-lo diretamente.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 14,
    total: 70,
    question: 'O que tem mÃ£os mas nÃ£o consegue bater palmas?',
    options: [
      { key: 'A', text: 'Um relÃ³gio' },
      { key: 'B', text: 'Um humano' },
      { key: 'C', text: 'Um macaco' },
      { key: 'D', text: 'Um pianista' },
    ],
    correct: 'A',
    explanation: 'Um relÃ³gio pode ter ponteiros chamados mÃ£os, mas nÃ£o bate palmas.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 15,
    total: 70,
    question: 'Um homem estÃ¡ debaixo de chuva sem guarda-chuva. Nem um fio de cabelo fica molhado. PorquÃª?',
    options: [
      { key: 'A', text: 'A chuva era falsa' },
      { key: 'B', text: 'Estava dentro de casa' },
      { key: 'C', text: 'Era careca' },
      { key: 'D', text: 'Usava laca' },
    ],
    correct: 'C',
    explanation: 'Se o homem Ã© careca, nÃ£o tem cabelo para ficar molhado.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 16,
    total: 70,
    question: 'O que tem uma boca mas nÃ£o come?',
    options: [
      { key: 'A', text: 'Um rio' },
      { key: 'B', text: 'Um cÃ£o' },
      { key: 'C', text: 'Uma crianÃ§a' },
      { key: 'D', text: 'Um peixe' },
    ],
    correct: 'A',
    explanation: 'A boca de um rio Ã© o local onde ele desagua.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 17,
    total: 70,
    question: 'Se tens 10 peixes num aquÃ¡rio e 3 morrem, quantos peixes ficam no aquÃ¡rio?',
    options: [
      { key: 'A', text: '7' },
      { key: 'B', text: '3' },
      { key: 'C', text: '10' },
      { key: 'D', text: 'Nenhum' },
    ],
    correct: 'C',
    explanation: 'Os trÃªs peixes morreram, mas continuam dentro do aquÃ¡rio.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 18,
    total: 70,
    question: 'Qual Ã© o animal que anda com as patas na cabeÃ§a?',
    options: [
      { key: 'A', text: 'O caranguejo' },
      { key: 'B', text: 'O piolho' },
      { key: 'C', text: 'O polvo' },
      { key: 'D', text: 'A galinha' },
    ],
    correct: 'B',
    explanation: 'O piolho desloca-se sobre a cabeÃ§a usando as suas patas.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 19,
    total: 70,
    question: 'Se um aviÃ£o cair exatamente na fronteira entre Portugal e Espanha, onde enterram os sobreviventes?',
    options: [
      { key: 'A', text: 'Portugal' },
      { key: 'B', text: 'Espanha' },
      { key: 'C', text: 'Na fronteira' },
      { key: 'D', text: 'NÃ£o enterram sobreviventes' },
    ],
    correct: 'D',
    explanation: 'Se sÃ£o sobreviventes, nÃ£o sÃ£o enterrados.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 20,
    total: 70,
    question: 'O que tem cidades, rios e montanhas, mas nÃ£o tem pessoas, Ã¡gua ou Ã¡rvores?',
    options: [
      { key: 'A', text: 'Um mapa' },
      { key: 'B', text: 'Um sonho' },
      { key: 'C', text: 'Um videojogo' },
      { key: 'D', text: 'Uma fotografia' },
    ],
    correct: 'A',
    explanation: 'Um mapa representa cidades, rios e montanhas.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 21,
    total: 70,
    question: 'O que tem um olho mas nÃ£o consegue ver?',
    options: [
      { key: 'A', text: 'Uma agulha' },
      { key: 'B', text: 'Um gato' },
      { key: 'C', text: 'Uma Ã¡guia' },
      { key: 'D', text: 'Uma pessoa' },
    ],
    correct: 'A',
    explanation: 'O buraco da agulha Ã© chamado de olho da agulha.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 22,
    total: 70,
    question: 'O que tem cabeÃ§a e cauda, mas nÃ£o tem corpo?',
    options: [
      { key: 'A', text: 'Uma moeda' },
      { key: 'B', text: 'Uma cobra' },
      { key: 'C', text: 'Um peixe' },
      { key: 'D', text: 'Um lagarto' },
    ],
    correct: 'A',
    explanation: 'Uma moeda pode ter uma face e uma cauda, sem ter um corpo.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 23,
    total: 70,
    question: 'O que podes apanhar mas nunca podes atirar?',
    options: [
      { key: 'A', text: 'Uma bola' },
      { key: 'B', text: 'Uma constipaÃ§Ã£o' },
      { key: 'C', text: 'Uma pedra' },
      { key: 'D', text: 'Um aviÃ£o' },
    ],
    correct: 'B',
    explanation: 'Podemos apanhar uma constipaÃ§Ã£o, mas nÃ£o a podemos atirar fisicamente.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 24,
    total: 70,
    question: 'O que corre mas nunca tem pernas?',
    options: [
      { key: 'A', text: 'Um atleta' },
      { key: 'B', text: 'Um rio' },
      { key: 'C', text: 'Um cÃ£o' },
      { key: 'D', text: 'Uma galinha' },
    ],
    correct: 'B',
    explanation: 'Dizemos que um rio corre apesar de nÃ£o ter pernas.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 25,
    total: 70,
    question: 'O que tem muitas chaves mas nÃ£o abre nenhuma porta?',
    options: [
      { key: 'A', text: 'Um molho de chaves' },
      { key: 'B', text: 'Um piano' },
      { key: 'C', text: 'Uma fechadura' },
      { key: 'D', text: 'Uma garagem' },
    ],
    correct: 'B',
    explanation: 'Um piano tem muitas teclas, mas nenhuma abre uma porta.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 26,
    total: 70,
    question: 'O que tem folhas mas nÃ£o Ã© uma Ã¡rvore?',
    options: [
      { key: 'A', text: 'Um livro' },
      { key: 'B', text: 'Uma pedra' },
      { key: 'C', text: 'Um sapato' },
      { key: 'D', text: 'Um copo' },
    ],
    correct: 'A',
    explanation: 'Um livro Ã© composto por folhas.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 27,
    total: 70,
    question: 'O que desaparece no momento em que acendes a luz?',
    options: [
      { key: 'A', text: 'A escuridÃ£o' },
      { key: 'B', text: 'O chÃ£o' },
      { key: 'C', text: 'O teto' },
      { key: 'D', text: 'O ar' },
    ],
    correct: 'A',
    explanation: 'Quando acendes a luz, a escuridÃ£o desaparece naquele espaÃ§o.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 28,
    total: 70,
    question: 'Qual destas coisas pode ser quebrada sem ser tocada?',
    options: [
      { key: 'A', text: 'Uma promessa' },
      { key: 'B', text: 'Um copo' },
      { key: 'C', text: 'Um prato' },
      { key: 'D', text: 'Uma janela' },
    ],
    correct: 'A',
    explanation: 'Uma promessa pode ser quebrada sem contacto fÃ­sico.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 29,
    total: 70,
    question: 'Se tens 5 velas acesas e apagas 2, quantas velas ficam?',
    options: [
      { key: 'A', text: '2' },
      { key: 'B', text: '3' },
      { key: 'C', text: '5' },
      { key: 'D', text: 'Nenhuma' },
    ],
    correct: 'C',
    explanation: 'Apagar duas velas nÃ£o faz com que desapareÃ§am. Continuam a existir as cinco.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 30,
    total: 70,
    question: 'Um mÃ©dico dÃ¡-te 3 comprimidos e diz para tomares um a cada meia hora. Quanto tempo demora a tomar os trÃªs?',
    options: [
      { key: 'A', text: '30 minutos' },
      { key: 'B', text: '1 hora' },
      { key: 'C', text: '1 hora e 30 minutos' },
      { key: 'D', text: '2 horas' },
    ],
    correct: 'B',
    explanation: 'Tomas o primeiro imediatamente, o segundo 30 minutos depois e o terceiro 30 minutos depois.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 31,
    total: 70,
    question: 'Se um relÃ³gio estiver parado, quantas vezes por dia mostra a hora certa?',
    options: [
      { key: 'A', text: 'Nenhuma' },
      { key: 'B', text: 'Uma' },
      { key: 'C', text: 'Duas' },
      { key: 'D', text: 'Vinte e quatro' },
    ],
    correct: 'C',
    explanation: 'Um relÃ³gio parado num horÃ¡rio de 12 horas coincide duas vezes por dia com a hora certa.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 32,
    total: 70,
    question: 'Qual Ã© o mÃªs que tem menos dias?',
    options: [
      { key: 'A', text: 'Janeiro' },
      { key: 'B', text: 'Fevereiro' },
      { key: 'C', text: 'Abril' },
      { key: 'D', text: 'Junho' },
    ],
    correct: 'B',
    explanation: 'Fevereiro Ã© o mÃªs com menos dias.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 33,
    total: 70,
    question: 'Se uma pessoa tem uma mÃ£o cheia de dedos, quantos dedos tem em duas mÃ£os?',
    options: [
      { key: 'A', text: '5' },
      { key: 'B', text: '8' },
      { key: 'C', text: '10' },
      { key: 'D', text: '12' },
    ],
    correct: 'C',
    explanation: 'Uma mÃ£o tem cinco dedos. Duas mÃ£os tÃªm dez.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 34,
    total: 70,
    question: 'O que Ã© que tem pernas mas nÃ£o anda?',
    options: [
      { key: 'A', text: 'Uma mesa' },
      { key: 'B', text: 'Um cÃ£o' },
      { key: 'C', text: 'Um cavalo' },
      { key: 'D', text: 'Uma pessoa' },
    ],
    correct: 'A',
    explanation: 'Uma mesa pode ter pernas, mas nÃ£o anda.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 35,
    total: 70,
    question: 'Qual Ã© a Ãºnica coisa que podes dar a alguÃ©m e continuar a ter?',
    options: [
      { key: 'A', text: 'Um abraÃ§o' },
      { key: 'B', text: 'Um carro' },
      { key: 'C', text: 'Uma casa' },
      { key: 'D', text: 'Uma moeda' },
    ],
    correct: 'A',
    explanation: 'Podes dar um abraÃ§o e continuar a poder abraÃ§ar.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 36,
    total: 70,
    question: 'Qual Ã© o lugar onde quinta vem antes de quarta?',
    options: [
      { key: 'A', text: 'Num calendÃ¡rio' },
      { key: 'B', text: 'Num dicionÃ¡rio' },
      { key: 'C', text: 'Na escola' },
      { key: 'D', text: 'Num relÃ³gio' },
    ],
    correct: 'B',
    explanation: 'Num dicionÃ¡rio, as palavras aparecem por ordem alfabÃ©tica.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 37,
    total: 70,
    question: 'Se tens uma caixa vazia e colocas uma coisa lÃ¡ dentro, continua vazia?',
    options: [
      { key: 'A', text: 'Sim' },
      { key: 'B', text: 'NÃ£o' },
      { key: 'C', text: 'SÃ³ Ã s segundas-feiras' },
      { key: 'D', text: 'Depende da cor da caixa' },
    ],
    correct: 'B',
    explanation: 'Depois de colocares alguma coisa lÃ¡ dentro, a caixa deixa de estar vazia.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 38,
    total: 70,
    question: 'Se tens 4 pernas de uma mesa, quantas pernas tem a mesa?',
    options: [
      { key: 'A', text: 'Uma' },
      { key: 'B', text: 'Duas' },
      { key: 'C', text: 'Quatro' },
      { key: 'D', text: 'Oito' },
    ],
    correct: 'C',
    explanation: 'A pergunta jÃ¡ diz que sÃ£o quatro pernas.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 39,
    total: 70,
    question: 'O que pode atravessar uma cidade inteira sem sair do lugar?',
    options: [
      { key: 'A', text: 'Uma estrada' },
      { key: 'B', text: 'Um carro' },
      { key: 'C', text: 'Um aviÃ£o' },
      { key: 'D', text: 'Um cÃ£o' },
    ],
    correct: 'A',
    explanation: 'Uma estrada pode atravessar uma cidade permanecendo no mesmo lugar.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 40,
    total: 70,
    question: 'O que sobe quando a chuva desce?',
    options: [
      { key: 'A', text: 'O guarda-chuva' },
      { key: 'B', text: 'O chÃ£o' },
      { key: 'C', text: 'O sofÃ¡' },
      { key: 'D', text: 'A televisÃ£o' },
    ],
    correct: 'A',
    explanation: 'Quando comeÃ§a a chover, levantamos ou abrimos o guarda-chuva.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 41,
    total: 70,
    question: 'O que tem cabeÃ§a e cauda, mas nÃ£o tem corpo?',
    options: [
      { key: 'A', text: 'Uma moeda' },
      { key: 'B', text: 'Um cÃ£o' },
      { key: 'C', text: 'Um peixe' },
      { key: 'D', text: 'Uma cobra' },
    ],
    correct: 'A',
    explanation: 'Uma moeda pode ser descrita como tendo cara e coroa, ou cabeÃ§a e cauda.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 42,
    total: 70,
    question: 'O que fica maior quanto mais tiras?',
    options: [
      { key: 'A', text: 'Um buraco' },
      { key: 'B', text: 'Um copo' },
      { key: 'C', text: 'Uma cadeira' },
      { key: 'D', text: 'Uma colher' },
    ],
    correct: 'A',
    explanation: 'Quanto mais material retiras de um buraco, maior ele fica.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 43,
    total: 70,
    question: 'O que tem uma cara e duas mÃ£os mas nÃ£o tem braÃ§os?',
    options: [
      { key: 'A', text: 'Um relÃ³gio' },
      { key: 'B', text: 'Um homem' },
      { key: 'C', text: 'Um boneco' },
      { key: 'D', text: 'Um jogador' },
    ],
    correct: 'A',
    explanation: 'Um relÃ³gio pode ter uma face e dois ponteiros chamados mÃ£os.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 44,
    total: 70,
    question: 'O que podes ver uma vez num minuto, duas vezes num momento e nunca numa hora?',
    options: [
      { key: 'A', text: 'A letra M' },
      { key: 'B', text: 'A letra O' },
      { key: 'C', text: 'A letra A' },
      { key: 'D', text: 'A letra R' },
    ],
    correct: 'A',
    explanation: 'A letra M aparece uma vez em â€œminutoâ€, duas vezes em â€œmomentoâ€ e nenhuma vez em â€œhoraâ€.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 45,
    total: 70,
    question: 'O que tem anel mas nÃ£o Ã© joia?',
    options: [
      { key: 'A', text: 'Um telefone' },
      { key: 'B', text: 'Uma batata' },
      { key: 'C', text: 'Uma almofada' },
      { key: 'D', text: 'Uma colher' },
    ],
    correct: 'A',
    explanation: 'Um telefone pode tocar e ter um toque de chamada, associado Ã  ideia de â€œringâ€.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 46,
    total: 70,
    question: 'Qual Ã© a coisa que quanto mais seca, mais molhada fica?',
    options: [
      { key: 'A', text: 'Uma toalha' },
      { key: 'B', text: 'Uma pedra' },
      { key: 'C', text: 'Uma mesa' },
      { key: 'D', text: 'Uma parede' },
    ],
    correct: 'A',
    explanation: 'A toalha absorve a Ã¡gua enquanto seca outras superfÃ­cies.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 47,
    total: 70,
    question: 'O que tem quatro pernas de manhÃ£, duas ao meio-dia e trÃªs Ã  noite?',
    options: [
      { key: 'A', text: 'Um cÃ£o' },
      { key: 'B', text: 'O ser humano' },
      { key: 'C', text: 'Uma mesa' },
      { key: 'D', text: 'Um gato' },
    ],
    correct: 'B',
    explanation: 'Ã‰ a conhecida metÃ¡fora da Esfinge: bebÃ© de quatro, adulto de duas e idoso com bengala.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 48,
    total: 70,
    question: 'O que tem um banco mas nÃ£o Ã© para sentar?',
    options: [
      { key: 'A', text: 'Um banco de dados' },
      { key: 'B', text: 'Uma cadeira' },
      { key: 'C', text: 'Uma cama' },
      { key: 'D', text: 'Um sofÃ¡' },
    ],
    correct: 'A',
    explanation: 'Um banco de dados tem â€œbancoâ€ no nome, mas nÃ£o serve para sentar.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 49,
    total: 70,
    question: 'Se um homem tem 10 dedos nas mÃ£os, quantos dedos tÃªm 10 homens?',
    options: [
      { key: 'A', text: '50' },
      { key: 'B', text: '100' },
      { key: 'C', text: '20' },
      { key: 'D', text: '10' },
    ],
    correct: 'B',
    explanation: '10 homens Ã— 10 dedos = 100 dedos.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 50,
    total: 70,
    question: 'Qual Ã© a coisa que quanto mais se aproxima, mais longe parece estar?',
    options: [
      { key: 'A', text: 'O horizonte' },
      { key: 'B', text: 'Uma parede' },
      { key: 'C', text: 'Uma porta' },
      { key: 'D', text: 'Uma cadeira' },
    ],
    correct: 'A',
    explanation: 'O horizonte parece afastar-se Ã  medida que nos aproximamos dele.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 51,
    total: 70,
    question: 'Se um pato usar botas, qual é a primeira coisa que provavelmente vai fazer?',
    options: [
      { key: 'A', text: 'Pedir um café' },
      { key: 'B', text: 'Andar de skate' },
      { key: 'C', text: 'Ficar a olhar para os pés' },
      { key: 'D', text: 'Voar para Marte' },
    ],
    correct: 'C',
    explanation: 'Se um pato nunca usou botas, é provável que observe as botas antes de mais.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 52,
    total: 70,
    question: 'O que acontece se colocares um frigorífico dentro de outro frigorífico?',
    options: [
      { key: 'A', text: 'Fica mais frio' },
      { key: 'B', text: 'Nasce um mini-frigorífico' },
      { key: 'C', text: 'O frigorífico de dentro pede para sair' },
      { key: 'D', text: 'Nada de especial' },
    ],
    correct: 'D',
    explanation: 'Meter um frigorífico dentro de outro não altera por si o funcionamento prático para além do espaço ocupado.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 53,
    total: 70,
    question: 'Se um peixe abrir uma conta bancária, qual será provavelmente o maior problema?',
    options: [
      { key: 'A', text: 'Não saber nadar' },
      { key: 'B', text: 'Não conseguir assinar o contrato com as barbatanas' },
      { key: 'C', text: 'Pagar impostos' },
      { key: 'D', text: 'O banco estar demasiado seco' },
    ],
    correct: 'D',
    explanation: 'Um banco fisicamente seco seria impróprio para um peixe; é uma resposta divertida alinhada ao absurdo da pergunta.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 54,
    total: 70,
    question: 'Qual destes animais teria mais dificuldade em esconder-se atrás de uma árvore fina?',
    options: [
      { key: 'A', text: 'Formiga' },
      { key: 'B', text: 'Rato' },
      { key: 'C', text: 'Elefante' },
      { key: 'D', text: 'Lagartixa' },
    ],
    correct: 'C',
    explanation: 'Um elefante é grande demais para se esconder atrás de uma árvore fina.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 55,
    total: 70,
    question: 'Se estiveres a correr numa corrida e ultrapassares a pessoa que está em segundo lugar, em que posição ficas?',
    options: [
      { key: 'A', text: 'Primeiro' },
      { key: 'B', text: 'Segundo' },
      { key: 'C', text: 'Terceiro' },
      { key: 'D', text: 'Depende da velocidade' },
    ],
    correct: 'B',
    explanation: 'Ao ultrapassares o segundo, passas a ocupar o segundo lugar.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 56,
    total: 70,
    question: 'Um homem entrou numa sala completamente molhado, mas não estava a chover. Porquê?',
    options: [
      { key: 'A', text: 'Tomou banho' },
      { key: 'B', text: 'Caiu numa piscina' },
      { key: 'C', text: 'Era um peixe' },
      { key: 'D', text: 'Entrou pela máquina de lavar' },
    ],
    correct: 'A',
    explanation: 'Tomar um banho é a explicação simples e aceitável para estar molhado fora de chuva.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 57,
    total: 70,
    question: 'Se uma galinha disser "miau", o que devemos fazer?',
    options: [
      { key: 'A', text: 'Chamar o veterinário' },
      { key: 'B', text: 'Dar-lhe leite' },
      { key: 'C', text: 'Procurar o gato' },
      { key: 'D', text: 'Nada, provavelmente está a experimentar' },
    ],
    correct: 'D',
    explanation: 'A resposta assume que é apenas um comportamento estranho ou um som inusitado.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 58,
    total: 70,
    question: 'Qual é a maneira mais rápida de fazer uma pizza desaparecer?',
    options: [
      { key: 'A', text: 'Com magia' },
      { key: 'B', text: 'Comê-la' },
      { key: 'C', text: 'Mandá-la para o espaço' },
      { key: 'D', text: 'Esconder a pizza' },
    ],
    correct: 'B',
    explanation: 'Comer a pizza é a forma mais direta de a fazer desaparecer.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 59,
    total: 70,
    question: 'Se o teu despertador tocar às 8:00 e estiveres a dormir, o que provavelmente acontece?',
    options: [
      { key: 'A', text: 'O despertador fica cansado' },
      { key: 'B', text: 'Acordas' },
      { key: 'C', text: 'O despertador vai trabalhar por ti' },
      { key: 'D', text: 'O tempo para' },
    ],
    correct: 'B',
    explanation: 'O objetivo de um despertador é acordar a pessoa que está a dormir.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 60,
    total: 70,
    question: 'Um homem tem quatro maçãs e tira duas. Quantas maçãs tem?',
    options: [
      { key: 'A', text: 'Duas' },
      { key: 'B', text: 'Quatro' },
      { key: 'C', text: 'Nenhuma' },
      { key: 'D', text: 'Depende de quem tirou as maçãs' },
    ],
    correct: 'A',
    explanation: 'Se tem quatro e tira duas, ficam-lhe duas.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 61,
    total: 70,
    question: 'Qual é a melhor maneira de ensinar um cão a contar até dez?',
    options: [
      { key: 'A', text: 'Explicar-lhe matemática' },
      { key: 'B', text: 'Dar-lhe uma calculadora' },
      { key: 'C', text: 'Não é garantido que ele queira aprender' },
      { key: 'D', text: 'Pôr-lhe um professor particular' },
    ],
    correct: 'C',
    explanation: 'Nem todos os cães se interessam por contagens; é uma resposta divertida e prudente.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 62,
    total: 70,
    question: 'Se uma vaca entrar num supermercado, qual destas coisas é mais provável acontecer?',
    options: [
      { key: 'A', text: 'Compra leite' },
      { key: 'B', text: 'Compra erva' },
      { key: 'C', text: 'Os clientes ficam surpreendidos' },
      { key: 'D', text: 'Vai diretamente à caixa multibanco' },
    ],
    correct: 'C',
    explanation: 'Ver uma vaca num supermercado é inesperado e surpreende os clientes.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 63,
    total: 70,
    question: 'O que pesa mais: um quilo de ferro ou um quilo de penas?',
    options: [
      { key: 'A', text: 'Ferro' },
      { key: 'B', text: 'Penas' },
      { key: 'C', text: 'Pesam o mesmo' },
      { key: 'D', text: 'Depende da galinha' },
    ],
    correct: 'C',
    explanation: 'Um quilo é um quilo, independentemente do material.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 64,
    total: 70,
    question: 'Se fechares os olhos e não conseguires ver nada, qual é a explicação mais provável?',
    options: [
      { key: 'A', text: 'A luz desapareceu do planeta' },
      { key: 'B', text: 'Os teus olhos estão fechados' },
      { key: 'C', text: 'Ficaste invisível' },
      { key: 'D', text: 'O mundo desligou' },
    ],
    correct: 'B',
    explanation: 'Fechar os olhos impede a visão, explicação simples e direta.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 65,
    total: 70,
    question: 'Um caracol participa numa corrida. Qual é a sua maior vantagem?',
    options: [
      { key: 'A', text: 'É extremamente rápido' },
      { key: 'B', text: 'Tem a casa às costas' },
      { key: 'C', text: 'Não precisa de estacionamento' },
      { key: 'D', text: 'Pode desistir lentamente' },
    ],
    correct: 'B',
    explanation: 'O caracol transporta a sua casa, o que é uma vantagem curiosa.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 66,
    total: 70,
    question: 'Se encontrares um pinguim no deserto, qual é a primeira coisa que provavelmente vais pensar?',
    options: [
      { key: 'A', text: 'Que está de férias' },
      { key: 'B', text: 'Que se perdeu' },
      { key: 'C', text: 'Que o deserto ficou mais frio' },
      { key: 'D', text: 'Que é uma miragem' },
    ],
    correct: 'B',
    explanation: 'Um pinguim fora do seu habitat sugere que está perdido.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 67,
    total: 70,
    question: 'Se uma pessoa comer uma sopa com um garfo, qual é o principal problema?',
    options: [
      { key: 'A', text: 'A sopa fica zangada' },
      { key: 'B', text: 'O garfo não é muito eficiente para sopa' },
      { key: 'C', text: 'O prato desaparece' },
      { key: 'D', text: 'A colher fica com ciúmes' },
    ],
    correct: 'B',
    explanation: 'Um garfo dificilmente permite apanhar sopa eficientemente.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 68,
    total: 70,
    question: 'Qual destes objetos seria mais estranho encontrar dentro de uma máquina de lavar roupa?',
    options: [
      { key: 'A', text: 'Uma meia' },
      { key: 'B', text: 'Uma camisola' },
      { key: 'C', text: 'Um elefante' },
      { key: 'D', text: 'Uma toalha' },
    ],
    correct: 'C',
    explanation: 'Um elefante é claramente demasiado grande para uma máquina de lavar doméstica.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 69,
    total: 70,
    question: 'Se um vampiro for ao dentista, qual é a maior preocupação?',
    options: [
      { key: 'A', text: 'Ter medo da cadeira' },
      { key: 'B', text: 'Descobrir que precisa de aparelho' },
      { key: 'C', text: 'O dentista reparar nos dentes' },
      { key: 'D', text: 'O dentista pedir-lhe para abrir a boca' },
    ],
    correct: 'C',
    explanation: 'Vampiros têm dentes peculiares; o dentista notar isso é o problema mais plausível.',
    points: 500,
  },
  {
    category: 'Modo Maluco',
    index: 70,
    total: 70,
    question: 'Se disseres "não digas esta frase", o que acabaste de fazer?',
    options: [
      { key: 'A', text: 'Nada' },
      { key: 'B', text: 'Disseste a frase' },
      { key: 'C', text: 'Mentiste' },
      { key: 'D', text: 'Criaste um paradoxo' },
    ],
    correct: 'B',
    explanation: 'Ao dizeres a frase proibida, acabaste por pronunciá-la.',
    points: 500,
  }]

export const DEMO_QUIZ: QuizQuestion[] = [
  {
    category: 'Geografia',
    index: 5,
    total: 20,
    question: 'Qual Ã© o distrito portuguÃªs com maior Ã¡rea?',
    options: [
      { key: 'A', text: 'BraganÃ§a' },
      { key: 'B', text: 'Beja' },
      { key: 'C', text: 'Ã‰vora' },
      { key: 'D', text: 'Viseu' },
    ],
    correct: 'B',
    explanation:
      'Beja Ã© o maior distrito de Portugal, com cerca de 10 225 kmÂ².',
    points: 500,
  },
  {
    category: 'HistÃ³ria',
    index: 6,
    total: 20,
    question:
      'Em que ano foi assinado o Tratado de Windsor entre Portugal e Inglaterra?',
    options: [
      { key: 'A', text: '1386' },
      { key: 'B', text: '1415' },
      { key: 'C', text: '1290' },
      { key: 'D', text: '1500' },
    ],
    correct: 'A',
    explanation:
      'O Tratado de Windsor foi assinado em 1386.',
    points: 500,
  },
]

export const ALL_QUIZ_QUESTIONS: QuizQuestion[] = [
  ...DEMO_QUIZ,
  ...MODO_MALUCO_QUESTIONS,
]

