import type { MapArenaPOI } from '@/components/portugal-map/types'
import { ARENA_SHOP_CATALOG, getOfficialArenaImage } from '@/src/data/shopArenas'

/**
 * Mapeamento Canónico e Geográfico das Arenas Oficiais do Acorda Portugal
 * Coordenadas WGS84 [lng, lat] em distritos e cidades reais de Portugal
 */
export const OFFICIAL_MAP_ARENAS: MapArenaPOI[] = [
  {
    id: 'arena_praca_liberdade',
    name: 'Praça da Liberdade',
    district: 'Porto',
    coordinates: [-8.611, 41.1469],
    rarity: 'Comum',
    image: getOfficialArenaImage('arena_praca_liberdade'),
    description: 'O pulsar cívico da Invicta, no coração da Avenida dos Aliados.',
    category: 'cidade',
  },
  {
    id: 'arena_ponte_d_luis',
    name: 'Ponte D. Luís I',
    district: 'Porto',
    coordinates: [-8.6095, 41.14],
    rarity: 'Rara',
    image: getOfficialArenaImage('arena_ponte_d_luis'),
    description: 'Ícone da engenharia de ferro sobre o Rio Douro unindo Porto e Gaia.',
    category: 'monumento',
  },
  {
    id: 'arena_castelo_dos_campeoes',
    name: 'Castelo de Guimarães (Berço)',
    district: 'Braga',
    coordinates: [-8.2902, 41.4478],
    rarity: 'Lendária',
    image: getOfficialArenaImage('arena_castelo_dos_campeoes'),
    description: 'O berço da nacionalidade onde nasceu Portugal sob o escudo de D. Afonso Henriques.',
    category: 'historia',
  },
  {
    id: 'arena_cidade_norte',
    name: 'Santuário do Bom Jesus',
    district: 'Braga',
    coordinates: [-8.3773, 41.5546],
    rarity: 'Rara',
    image: getOfficialArenaImage('arena_cidade_norte'),
    description: 'Escadaria monumental barroca e património mundial no Minho.',
    category: 'monumento',
  },
  {
    id: 'arena_lisboa_imperial',
    name: 'Praça do Comércio (Terreiro do Paço)',
    district: 'Lisboa',
    coordinates: [-9.1366, 38.7075],
    rarity: 'Épica',
    image: getOfficialArenaImage('arena_lisboa_imperial'),
    description: 'A nobreza imperial de Lisboa aberta às águas do Estuário do Tejo.',
    category: 'cidade',
  },
  {
    id: 'arena_torre_belem',
    name: 'Torre de Belém',
    district: 'Lisboa',
    coordinates: [-9.216, 38.6916],
    rarity: 'Lendária',
    image: getOfficialArenaImage('arena_torre_belem'),
    description: 'Guardiã dos mares manuelina e ponto de partida das caravelas lusitanas.',
    category: 'monumento',
  },
  {
    id: 'arena_palacio_nacional',
    name: 'Palácio da Pena & Sintra Real',
    district: 'Lisboa',
    coordinates: [-9.3907, 38.7877],
    rarity: 'Exclusiva',
    image: getOfficialArenaImage('arena_palacio_nacional'),
    description: 'O castelo de conto de fadas romântico envolto nas névoas da Serra de Sintra.',
    category: 'monumento',
  },
  {
    id: 'arena_castelo_obidos',
    name: 'Muralhas de Óbidos',
    district: 'Leiria',
    coordinates: [-9.1575, 39.3622],
    rarity: 'Rara',
    image: getOfficialArenaImage('arena_castelo_obidos'),
    description: 'Cidadela medieval fortificada de ruas brancas e ameias de pedra.',
    category: 'historia',
  },
  {
    id: 'arena_mosteiro_antigo',
    name: 'Mosteiro da Batalha',
    district: 'Leiria',
    coordinates: [-8.8258, 39.6599],
    rarity: 'Épica',
    image: getOfficialArenaImage('arena_mosteiro_antigo'),
    description: 'Obra-prima do gótico e manuelino erguida em celebração de Aljubarrota.',
    category: 'historia',
  },
  {
    id: 'arena_caos_patos',
    name: 'Canais da Ria de Aveiro',
    district: 'Aveiro',
    coordinates: [-8.6538, 40.6405],
    rarity: 'Comum',
    image: getOfficialArenaImage('arena_caos_patos'),
    description: 'Labirinto aquático de moliceiros, salinas e reflexos da Ria.',
    category: 'natureza',
  },
  {
    id: 'arena_portugal_medieval',
    name: 'Paço das Escolas de Coimbra',
    district: 'Coimbra',
    coordinates: [-8.4262, 40.2075],
    rarity: 'Épica',
    image: getOfficialArenaImage('arena_portugal_medieval'),
    description: 'Uma das mais antigas universidades da Europa e bastião da sabedoria lusa.',
    category: 'historia',
  },
  {
    id: 'arena_pico_estrelas',
    name: 'Torre da Serra da Estrela',
    district: 'Guarda',
    coordinates: [-7.6133, 40.3217],
    rarity: 'Lendária',
    image: getOfficialArenaImage('arena_pico_estrelas'),
    description: 'O ponto mais alto de Portugal Continental (1993m), coroado pela neve e rochedos graníticos.',
    category: 'natureza',
  },
  {
    id: 'arena_corte_portuguesa',
    name: 'Cava de Viriato',
    district: 'Viseu',
    coordinates: [-7.9125, 40.6653],
    rarity: 'Rara',
    image: getOfficialArenaImage('arena_corte_portuguesa'),
    description: 'Trincheiras míticas da resistência dos Lusitanos frente às legiões romanas.',
    category: 'historia',
  },
  {
    id: 'arena_batalha_medieval',
    name: 'Castelo de Almourol',
    district: 'Santarém',
    coordinates: [-8.3839, 39.4619],
    rarity: 'Lendária',
    image: getOfficialArenaImage('arena_batalha_medieval'),
    description: 'Fortaleza templária erguida numa ilha escarpada no meio do Rio Tejo.',
    category: 'historia',
  },
  {
    id: 'arena_trono_real',
    name: 'Ninho das Águias de Marvão',
    district: 'Portalegre',
    coordinates: [-7.3778, 39.3942],
    rarity: 'Exclusiva',
    image: getOfficialArenaImage('arena_trono_real'),
    description: 'Fortaleza no cume da Serra de São Mamede de onde se avista a raia sem fim.',
    category: 'historia',
  },
  {
    id: 'arena_ceu_lusitano',
    name: 'Templo Romano de Évora',
    district: 'Évora',
    coordinates: [-7.9068, 38.5726],
    rarity: 'Épica',
    image: getOfficialArenaImage('arena_ceu_lusitano'),
    description: 'Colunas coríntias milenares sob o céu límpido da planície alentejana.',
    category: 'historia',
  },
  {
    id: 'arena_costa_selvagem',
    name: 'Portinho da Arrábida',
    district: 'Setúbal',
    coordinates: [-8.9839, 38.4831],
    rarity: 'Rara',
    image: getOfficialArenaImage('arena_costa_selvagem'),
    description: 'Águas cristalinas protegidas pela escarpa verdejante do Parque Natural da Arrábida.',
    category: 'natureza',
  },
  {
    id: 'arena_costa_atlantica',
    name: 'Promontório de Sagres & São Vicente',
    district: 'Faro',
    coordinates: [-8.9298, 37.0135],
    rarity: 'Épica',
    image: getOfficialArenaImage('arena_costa_atlantica'),
    description: 'O fim da Europa continental onde os ventos do Atlântico sussurram lendas de navegadores.',
    category: 'natureza',
  },
  {
    id: 'arena_vulcao_erupcao',
    name: 'Cratera Vulcânica das Furnas',
    district: 'Açores',
    coordinates: [-25.3283, 37.7656],
    rarity: 'Lendária',
    image: getOfficialArenaImage('arena_vulcao_erupcao'),
    description: 'Fumarolas ativas e caldeiras termais no coração vulcânico da Ilha de São Miguel.',
    category: 'natureza',
  },
  {
    id: 'arena_madeira_tropical',
    name: 'Floresta Laurissilva & Ponta de São Lourenço',
    district: 'Madeira',
    coordinates: [-16.9089, 32.65],
    rarity: 'Lendária',
    image: getOfficialArenaImage('arena_madeira_tropical'),
    description: 'Penhascos escarpados no Atlântico profundo e a lendária floresta terciária da Pérola do Oceano.',
    category: 'natureza',
  },
  {
    id: 'arena_ponte_2077',
    name: 'Lisboa Cybercore 2150',
    district: 'Lisboa',
    coordinates: [-9.095, 38.768],
    rarity: 'Lendária',
    image: getOfficialArenaImage('arena_ponte_2077'),
    description: 'A metrópole futurista com vias elevadas e arranha-céus no Parque das Nações.',
    category: 'futuro',
  },
  {
    id: 'arena_santa_luzia',
    name: 'Santuário de Santa Luzia & Foz do Lima',
    district: 'Viana do Castelo',
    coordinates: [-8.8353, 41.7019],
    rarity: 'Épica',
    image: getOfficialArenaImage('arena_era_descobrimentos'),
    description: 'Bastião do Alto Minho coroando a foz do Rio Lima frente ao oceano infinito.',
    category: 'monumento',
  },
  {
    id: 'arena_solar_mateus',
    name: 'Solar de Mateus & Alto Douro',
    district: 'Vila Real',
    coordinates: [-7.7183, 41.2969],
    rarity: 'Rara',
    image: getOfficialArenaImage('arena_final_nacional'),
    description: 'Arquitetura barroca singular guardando as encostas heroicas do Douro Vinhateiro.',
    category: 'monumento',
  },
  {
    id: 'arena_cidadela_braganca',
    name: 'Cidadela Medieval & Domus Municipalis',
    district: 'Bragança',
    coordinates: [-6.7497, 41.8039],
    rarity: 'Lendária',
    image: getOfficialArenaImage('arena_excl_fundadores'),
    description: 'Fortaleza granítica inexpugnável no cume transmontano do Nordeste.',
    category: 'historia',
  },
  {
    id: 'arena_monsanto_castelo',
    name: 'Aldeia Histórica de Monsanto & Raia',
    district: 'Castelo Branco',
    coordinates: [-7.1154, 40.0389],
    rarity: 'Épica',
    image: getOfficialArenaImage('arena_megalopolis_lusa'),
    description: 'A aldeia mais portuguesa esculpida entre gigantescos blocos graníticos da Beira Baixa.',
    category: 'historia',
  },
  {
    id: 'arena_torre_beja',
    name: 'Torre de Menagem de Beja & Planície',
    district: 'Beja',
    coordinates: [-7.8643, 38.0169],
    rarity: 'Rara',
    image: getOfficialArenaImage('arena_cyber_laboratorio'),
    description: 'A mais imponente torre gótica de Portugal dominando a vastidão da planície alentejana.',
    category: 'monumento',
  },
]

export function getArenaPOIById(arenaId: string): MapArenaPOI | undefined {
  if (!arenaId) return undefined
  const clean = arenaId.trim().toLowerCase()
  return OFFICIAL_MAP_ARENAS.find(
    (a) => a.id.toLowerCase() === clean || a.name.toLowerCase() === clean
  )
}

export function getArenasByDistrict(districtNameOrSlug: string): MapArenaPOI[] {
  if (!districtNameOrSlug) return []
  const clean = districtNameOrSlug.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim()
  return OFFICIAL_MAP_ARENAS.filter((a) => {
    const dClean = a.district.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim()
    return dClean === clean || clean.includes(dClean) || dClean.includes(clean)
  })
}
