export interface TerritoryMetadata {
  id: string
  name: string
  canonicalName: string
  type: 'mainland' | 'island'
  center: [number, number] // [lng, lat]
  zoom: number
  pitch: number
  bearing: number
  dominantColor: string
  accentColor: string
  capital: string
  motto: string
  region: 'Norte' | 'Centro' | 'Lisboa e Vale do Tejo' | 'Alentejo' | 'Algarve' | 'Açores' | 'Madeira'
  tacticalCode: string
}

export const TERRITORY_METADATA: Record<string, TerritoryMetadata> = {
  aveiro: {
    id: 'aveiro',
    name: 'Aveiro',
    canonicalName: 'Aveiro',
    type: 'mainland',
    center: [-8.6538, 40.6405],
    zoom: 9.2,
    pitch: 60,
    bearing: -10,
    dominantColor: '#38bdf8',
    accentColor: '#0284c7',
    capital: 'Aveiro',
    motto: 'Veneza de Portugal & Rota dos Moliceiros',
    region: 'Centro',
    tacticalCode: 'AV',
  },
  beja: {
    id: 'beja',
    name: 'Beja',
    canonicalName: 'Beja',
    type: 'mainland',
    center: [-7.8632, 38.0151],
    zoom: 8.4,
    pitch: 58,
    bearing: 5,
    dominantColor: '#eab308',
    accentColor: '#ca8a04',
    capital: 'Beja',
    motto: 'Coração Dourado do Baixo Alentejo',
    region: 'Alentejo',
    tacticalCode: 'BJ',
  },
  braga: {
    id: 'braga',
    name: 'Braga',
    canonicalName: 'Braga',
    type: 'mainland',
    center: [-8.4265, 41.5454],
    zoom: 9.3,
    pitch: 62,
    bearing: -15,
    dominantColor: '#ef4444',
    accentColor: '#b91c1c',
    capital: 'Braga',
    motto: 'Cidade dos Arcebispos & Berço Guerreiro',
    region: 'Norte',
    tacticalCode: 'BG',
  },
  braganca: {
    id: 'braganca',
    name: 'Bragança',
    canonicalName: 'Bragança',
    type: 'mainland',
    center: [-6.7572, 41.8058],
    zoom: 8.8,
    pitch: 55,
    bearing: 20,
    dominantColor: '#f97316',
    accentColor: '#c2410c',
    capital: 'Bragança',
    motto: 'Baluarte Transmontano & Sentinela do Nordeste',
    region: 'Norte',
    tacticalCode: 'BR',
  },
  castelo_branco: {
    id: 'castelo_branco',
    name: 'Castelo Branco',
    canonicalName: 'Castelo Branco',
    type: 'mainland',
    center: [-7.4912, 39.8222],
    zoom: 8.7,
    pitch: 57,
    bearing: 10,
    dominantColor: '#10b981',
    accentColor: '#047857',
    capital: 'Castelo Branco',
    motto: 'Guardiã da Beira Baixa & Fronteira Heroica',
    region: 'Centro',
    tacticalCode: 'CB',
  },
  coimbra: {
    id: 'coimbra',
    name: 'Coimbra',
    canonicalName: 'Coimbra',
    type: 'mainland',
    center: [-8.4103, 40.2033],
    zoom: 9.1,
    pitch: 60,
    bearing: -5,
    dominantColor: '#6366f1',
    accentColor: '#4338ca',
    capital: 'Coimbra',
    motto: 'Cidade dos Doutores & Trono do Conhecimento',
    region: 'Centro',
    tacticalCode: 'CO',
  },
  evora: {
    id: 'evora',
    name: 'Évora',
    canonicalName: 'Évora',
    type: 'mainland',
    center: [-7.9071, 38.5714],
    zoom: 8.6,
    pitch: 56,
    bearing: 0,
    dominantColor: '#f59e0b',
    accentColor: '#d97706',
    capital: 'Évora',
    motto: 'Templo de Diana & Joia Alentejana',
    region: 'Alentejo',
    tacticalCode: 'EV',
  },
  faro: {
    id: 'faro',
    name: 'Faro',
    canonicalName: 'Faro',
    type: 'mainland',
    center: [-7.9304, 37.0194],
    zoom: 9.0,
    pitch: 58,
    bearing: 15,
    dominantColor: '#0ea5e9',
    accentColor: '#0284c7',
    capital: 'Faro',
    motto: 'Costa Dourada & Bastião do Algarve',
    region: 'Algarve',
    tacticalCode: 'FR',
  },
  guarda: {
    id: 'guarda',
    name: 'Guarda',
    canonicalName: 'Guarda',
    type: 'mainland',
    center: [-7.2684, 40.5373],
    zoom: 8.9,
    pitch: 64,
    bearing: 12,
    dominantColor: '#ec4899',
    accentColor: '#be185d',
    capital: 'Guarda',
    motto: 'A Mais Alta & Mais Nobre Sentinela da Beira',
    region: 'Centro',
    tacticalCode: 'GD',
  },
  leiria: {
    id: 'leiria',
    name: 'Leiria',
    canonicalName: 'Leiria',
    type: 'mainland',
    center: [-8.8078, 39.7436],
    zoom: 9.0,
    pitch: 59,
    bearing: -8,
    dominantColor: '#d946ef',
    accentColor: '#a21caf',
    capital: 'Leiria',
    motto: 'Castelo Templário & Pinhal do Rei',
    region: 'Centro',
    tacticalCode: 'LR',
  },
  lisboa: {
    id: 'lisboa',
    name: 'Lisboa',
    canonicalName: 'Lisboa',
    type: 'mainland',
    center: [-9.1393, 38.7223],
    zoom: 9.6,
    pitch: 65,
    bearing: -12,
    dominantColor: '#f59e0b',
    accentColor: '#b45309',
    capital: 'Lisboa',
    motto: 'Capital Imperial & Coração do Império Lusitano',
    region: 'Lisboa e Vale do Tejo',
    tacticalCode: 'LX',
  },
  portalegre: {
    id: 'portalegre',
    name: 'Portalegre',
    canonicalName: 'Portalegre',
    type: 'mainland',
    center: [-7.4325, 39.2938],
    zoom: 8.8,
    pitch: 57,
    bearing: 8,
    dominantColor: '#84cc16',
    accentColor: '#4d7c0f',
    capital: 'Portalegre',
    motto: 'Sentinela do Alto Alentejo & Forte de São Mamede',
    region: 'Alentejo',
    tacticalCode: 'PT',
  },
  porto: {
    id: 'porto',
    name: 'Porto',
    canonicalName: 'Porto',
    type: 'mainland',
    center: [-8.6291, 41.1579],
    zoom: 9.5,
    pitch: 63,
    bearing: -18,
    dominantColor: '#06b6d4',
    accentColor: '#0e7490',
    capital: 'Porto',
    motto: 'Invicta & Berço da Nação Heroica',
    region: 'Norte',
    tacticalCode: 'PR',
  },
  santarem: {
    id: 'santarem',
    name: 'Santarém',
    canonicalName: 'Santarém',
    type: 'mainland',
    center: [-8.6845, 39.2367],
    zoom: 8.9,
    pitch: 58,
    bearing: -4,
    dominantColor: '#2dd4bf',
    accentColor: '#0f766e',
    capital: 'Santarém',
    motto: 'Capital do Gótico & Ribatejo Imortal',
    region: 'Alentejo',
    tacticalCode: 'SN',
  },
  setubal: {
    id: 'setubal',
    name: 'Setúbal',
    canonicalName: 'Setúbal',
    type: 'mainland',
    center: [-8.8882, 38.5244],
    zoom: 9.1,
    pitch: 61,
    bearing: -6,
    dominantColor: '#0284c7',
    accentColor: '#0369a1',
    capital: 'Setúbal',
    motto: 'Baía dos Golfinhos & Trono da Arrábida',
    region: 'Lisboa e Vale do Tejo',
    tacticalCode: 'ST',
  },
  viana_do_castelo: {
    id: 'viana_do_castelo',
    name: 'Viana do Castelo',
    canonicalName: 'Viana do Castelo',
    type: 'mainland',
    center: [-8.8329, 41.6918],
    zoom: 9.2,
    pitch: 61,
    bearing: -20,
    dominantColor: '#14b8a6',
    accentColor: '#0f766e',
    capital: 'Viana do Castelo',
    motto: 'Coração do Minho & Princesa do Lima',
    region: 'Norte',
    tacticalCode: 'VC',
  },
  vila_real: {
    id: 'vila_real',
    name: 'Vila Real',
    canonicalName: 'Vila Real',
    type: 'mainland',
    center: [-7.7441, 41.3006],
    zoom: 9.0,
    pitch: 62,
    bearing: 5,
    dominantColor: '#a855f7',
    accentColor: '#7e22ce',
    capital: 'Vila Real',
    motto: 'Porta de Trás-os-Montes & Reino Maravilhoso',
    region: 'Norte',
    tacticalCode: 'VR',
  },
  viseu: {
    id: 'viseu',
    name: 'Viseu',
    canonicalName: 'Viseu',
    type: 'mainland',
    center: [-7.9141, 40.6566],
    zoom: 9.0,
    pitch: 60,
    bearing: 0,
    dominantColor: '#84cc16',
    accentColor: '#65a30d',
    capital: 'Viseu',
    motto: 'Cidade de Viriato & Coração da Beira Alta',
    region: 'Centro',
    tacticalCode: 'VS',
  },
  acores: {
    id: 'acores',
    name: 'Açores',
    canonicalName: 'Açores',
    type: 'island',
    center: [-25.6687, 37.7412],
    zoom: 7.8,
    pitch: 52,
    bearing: 0,
    dominantColor: '#14b8a6',
    accentColor: '#0d9488',
    capital: 'Ponta Delgada',
    motto: 'Nove Ilhas de Bruma & Trono Atlântico',
    region: 'Açores',
    tacticalCode: 'AO',
  },
  madeira: {
    id: 'madeira',
    name: 'Madeira',
    canonicalName: 'Madeira',
    type: 'island',
    center: [-16.9085, 32.6500],
    zoom: 8.5,
    pitch: 56,
    bearing: 0,
    dominantColor: '#06b6d4',
    accentColor: '#0891b2',
    capital: 'Funchal',
    motto: 'Pérola do Atlântico & Bastião das Descobertas',
    region: 'Madeira',
    tacticalCode: 'MD',
  },
}

export const REGION_CAMERA_PRESETS = {
  continente: {
    center: [-7.95, 39.60] as [number, number],
    zoom: 6.8,
    pitch: 48,
    bearing: -6,
  },
  norte: {
    center: [-7.95, 41.35] as [number, number],
    zoom: 8.2,
    pitch: 58,
    bearing: -10,
  },
  centro: {
    center: [-8.15, 40.10] as [number, number],
    zoom: 8.1,
    pitch: 56,
    bearing: -4,
  },
  lisboa_vale_tejo: {
    center: [-8.95, 38.80] as [number, number],
    zoom: 8.8,
    pitch: 62,
    bearing: -12,
  },
  alentejo: {
    center: [-7.85, 38.30] as [number, number],
    zoom: 7.9,
    pitch: 54,
    bearing: 2,
  },
  algarve: {
    center: [-8.05, 37.15] as [number, number],
    zoom: 8.9,
    pitch: 58,
    bearing: 10,
  },
  acores: {
    center: [-25.67, 37.74] as [number, number],
    zoom: 7.8,
    pitch: 52,
    bearing: 0,
  },
  madeira: {
    center: [-16.91, 32.65] as [number, number],
    zoom: 8.5,
    pitch: 56,
    bearing: 0,
  },
}

export function getTerritoryMetadata(idOrName: string): TerritoryMetadata | undefined {
  const norm = idOrName.toLowerCase().trim()
  return (
    TERRITORY_METADATA[norm] ||
    Object.values(TERRITORY_METADATA).find(
      (m) => m.name.toLowerCase() === norm || m.canonicalName.toLowerCase() === norm || m.id === norm
    )
  )
}

export function getAllTerritoriesMetadataList(): TerritoryMetadata[] {
  return Object.values(TERRITORY_METADATA)
}

export const getTerritoryByName = getTerritoryMetadata
export const getAllTerritoriesList = getAllTerritoriesMetadataList

