import fs from 'fs'
import path from 'path'

export const ARENA_IMAGES_MAP: Record<string, string> = {
  arena_praca_liberdade: '/arenas/praca-liberdade.jpg',
  arena_castelo_obidos: '/arenas/castelo-obidos.jpg',
  arena_costa_atlantica: '/arenas/costa-atlantica.jpg',
  arena_ponte_d_luis: '/arenas/ponte-d-luis.jpg',
  arena_lisboa_imperial: '/arenas/lisboa-imperial.jpg',
  arena_torre_belem: '/arenas/torre-belem.jpg',
  arena_lisboa_imperial_noturna: '/arenas/arena-lisboa-imperial.jpg',
  arena_ponte_douro_panoramica: '/arenas/arena-ponte-d-luis.jpg',
  arena_cidade_norte: '/arenas/arena-3.jpg',
  arena_vulcao_erupcao: '/arenas/vulcao-acores.jpg',
  arena_vulcao_furnas: '/arenas/arena-vulcao-erupcao.jpg',
  arena_madeira_tropical: '/arenas/madeira-tropical.jpg',
  arena_pico_estrelas: '/arenas/pico-estrelas.jpg',
  arena_madeira_noite: '/arenas/madeira-noite.jpg',
  arena_pico_aurora: '/arenas/arena-pico-estrelas.jpg',
  arena_costa_selvagem: '/arenas/arena-4.jpg',
  arena_portugal_medieval: '/arenas/portugal-medieval.jpg',
  arena_era_descobrimentos: '/arenas/era-descobrimentos.jpg',
  arena_batalha_medieval: '/arenas/batalha-medieval.jpg',
  arena_corte_portuguesa: '/arenas/corte-portuguesa.jpg',
  arena_mosteiro_antigo: '/arenas/arena-5.jpg',
  arena_festival_portugues: '/arenas/festival-santos.jpg',
  arena_fado_alfama: '/arenas/fado-alfama.jpg',
  arena_teatro_nacional: '/arenas/teatro-nacional.jpg',
  arena_estadio_nacional: '/arenas/estadio-jamor.jpg',
  arena_noite_jogo: '/arenas/derbi-noite.jpg',
  arena_final_nacional: '/arenas/final-campeoes.jpg',
  arena_noite_selecao: '/arenas/conquista-selecao.jpg',
  arena_duelo_1v1_oficial: '/arenas/arena-1v1.png',
  arena_ponte_2077: '/arenas/ponte-2077.jpg',
  arena_lisboa_cybercore: '/arenas/lisboa-cybercore.jpg',
  arena_estacao_orbital: '/arenas/estacao-orbital.jpg',
  arena_portal_galactico: '/arenas/portal-galactico.jpg',
  arena_cyber_laboratorio: '/arenas/arena-7.jpg',
  arena_megalopolis_lusa: '/arenas/arena-10.jpg',
  arena_portugal_ao_contrario: '/arenas/portugal-invertido.jpg',
  arena_caos_patos: '/arenas/patos-aveiro.jpg',
  arena_dentro_cerebro: '/arenas/dentro-cerebro.jpg',
  arena_dimensao_psicadelica: '/arenas/arena-8.jpg',
  arena_labirinto_onirico: '/arenas/arena-9.jpg',
  arena_excl_campeao: '/arenas/trono-campeao.jpg',
  arena_excl_fundadores: '/arenas/monumento-fundadores.jpg',
  arena_excl_lenda_100: '/arenas/coliseu-100.jpg',
}

interface ArenaDef {
  id: string
  name: string
  description: string
  meaning: string
  theme: string
  image: string
  accent: string
  icon: string
  category: 'portugal' | 'ilhas' | 'historia' | 'cultura' | 'futebol' | 'futuristas' | 'maluco' | 'exclusivas'
  categoryLabel: string
  rarity: 'Comum' | 'Rara' | 'Épica' | 'Lendária' | 'Mítica' | 'Exclusiva'
  price: number | null
  unlockCondition?: string
  unlockedByDefault?: boolean
  unlocked?: boolean
  difficulty: 'Fácil' | 'Médio' | 'Difícil' | 'Extremo' | 'Lendário'
  environment: 'outdoor' | 'monument' | 'ocean' | 'nature' | 'stadium' | 'sci-fi' | 'fantasy'
  effect: 'particles' | 'rain' | 'fire' | 'lava' | 'snow' | 'lightning' | 'stars' | 'waves' | 'fog' | 'fireworks' | 'none'
  available: boolean
  order: number
}

// 43 Arenas Únicas Oficiais
const CATALOG_43: ArenaDef[] = [
  // ==========================================
  // 1. PORTUGAL & CIDADES (9 Arenas)
  // ==========================================
  {
    id: 'arena_praca_liberdade',
    name: 'Praça da Liberdade',
    description: 'O pulsar histórico e cívico da Invicta sob a luz solar dourada e o granito do Norte.',
    meaning: 'Consagração da coragem portuense e das lutas liberais que moldaram a liberdade de Portugal.',
    theme: 'cidades',
    image: ARENA_IMAGES_MAP.arena_praca_liberdade,
    accent: '#F59E0B',
    icon: '🏛️',
    category: 'portugal',
    categoryLabel: 'Portugal',
    rarity: 'Comum',
    price: 0,
    unlockedByDefault: true,
    unlocked: true,
    difficulty: 'Fácil',
    environment: 'monument',
    effect: 'particles',
    available: true,
    order: 1,
  },
  {
    id: 'arena_castelo_obidos',
    name: 'Castelo de Óbidos',
    description: 'Muralhas ameadas e tochas acesas ao anoitecer, guardando séculos de lendas reais.',
    meaning: 'A sentinela de pedra da Reconquista e o histórico dote das Rainhas de Portugal.',
    theme: 'historia',
    image: ARENA_IMAGES_MAP.arena_castelo_obidos,
    accent: '#EA580C',
    icon: '🏰',
    category: 'portugal',
    categoryLabel: 'Portugal',
    rarity: 'Épica',
    price: 7500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'monument',
    effect: 'fire',
    available: true,
    order: 2,
  },
  {
    id: 'arena_costa_atlantica',
    name: 'Costa Atlântica & Gigantes da Nazaré',
    description: 'A força indomável do oceano a embater nas falésias e no forte de São Miguel Arcanjo.',
    meaning: 'O confronto épico entre a coragem humana e as maiores ondas do planeta Terra.',
    theme: 'natureza',
    image: ARENA_IMAGES_MAP.arena_costa_atlantica,
    accent: '#06B6D4',
    icon: '🌊',
    category: 'portugal',
    categoryLabel: 'Portugal',
    rarity: 'Rara',
    price: 3500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'ocean',
    effect: 'waves',
    available: true,
    order: 3,
  },
  {
    id: 'arena_ponte_d_luis',
    name: 'Ponte D. Luís I',
    description: 'A icónica estrutura de ferro sobre o Rio Douro, unindo o Porto e Gaia sob o pôr do sol.',
    meaning: 'Símbolo da engenharia e do comércio mundial que transportou o Vinho do Porto para os quatro cantos.',
    theme: 'cidades',
    image: ARENA_IMAGES_MAP.arena_ponte_d_luis,
    accent: '#3B82F6',
    icon: '🌉',
    category: 'portugal',
    categoryLabel: 'Portugal',
    rarity: 'Rara',
    price: 4500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Fácil',
    environment: 'outdoor',
    effect: 'particles',
    available: true,
    order: 4,
  },
  {
    id: 'arena_lisboa_imperial',
    name: 'Terreiro do Paço Imperial',
    description: 'A majestosa praça pombalina aberta ao Tejo, coroada pelo Arco Triunfal da Rua Augusta.',
    meaning: 'O coração monumental da capital renascida das cinzas do Terramoto de 1755.',
    theme: 'cidades',
    image: ARENA_IMAGES_MAP.arena_lisboa_imperial,
    accent: '#EAB308',
    icon: '👑',
    category: 'portugal',
    categoryLabel: 'Portugal',
    rarity: 'Lendária',
    price: 15000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'monument',
    effect: 'particles',
    available: true,
    order: 5,
  },
  {
    id: 'arena_torre_belem',
    name: 'Torre de Belém & Padrão',
    description: 'A sentinela manuelina nas águas do Tejo de onde partiram as caravelas para o mundo.',
    meaning: 'O marco zero da epopeia marítima e património da humanidade em Lisboa.',
    theme: 'historia',
    image: ARENA_IMAGES_MAP.arena_torre_belem,
    accent: '#F97316',
    icon: '🧭',
    category: 'portugal',
    categoryLabel: 'Portugal',
    rarity: 'Lendária',
    price: 18500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'monument',
    effect: 'waves',
    available: true,
    order: 6,
  },
  {
    id: 'arena_lisboa_imperial_noturna',
    name: 'Lisboa Noturna & Tejo',
    description: 'A capital iluminada pelas luzes douradas ao longo da margem sul e do estuário do Tejo.',
    meaning: 'A serenidade e o mistério das noites lisboetas sobre o reflexo das águas.',
    theme: 'cidades',
    image: ARENA_IMAGES_MAP.arena_lisboa_imperial_noturna,
    accent: '#818CF8',
    icon: '🌃',
    category: 'portugal',
    categoryLabel: 'Portugal',
    rarity: 'Rara',
    price: 5000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'outdoor',
    effect: 'particles',
    available: true,
    order: 7,
  },
  {
    id: 'arena_ponte_douro_panoramica',
    name: 'Miradouro da Ponte do Douro',
    description: 'Vista panorâmica arrebatadora sobre as encostas vinícolas e as pontes metálicas do Porto.',
    meaning: 'O cruzamento entre o património mundial e a beleza natural do vale duriense.',
    theme: 'cidades',
    image: ARENA_IMAGES_MAP.arena_ponte_douro_panoramica,
    accent: '#38BDF8',
    icon: '🍇',
    category: 'portugal',
    categoryLabel: 'Portugal',
    rarity: 'Épica',
    price: 8000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'outdoor',
    effect: 'particles',
    available: true,
    order: 8,
  },
  {
    id: 'arena_cidade_norte',
    name: 'Coração de Pedra do Norte',
    description: 'Arquitetura clássica de granito cinzento e praças históricas das cidades do Norte de Portugal.',
    meaning: 'A nobreza e a firmeza das gentes do Norte que alicerçaram a fundação do reino.',
    theme: 'cidades',
    image: ARENA_IMAGES_MAP.arena_cidade_norte,
    accent: '#64748B',
    icon: '⛪',
    category: 'portugal',
    categoryLabel: 'Portugal',
    rarity: 'Comum',
    price: 1500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Fácil',
    environment: 'outdoor',
    effect: 'particles',
    available: true,
    order: 9,
  },

  // ==========================================
  // 2. ILHAS & NATUREZA (7 Arenas)
  // ==========================================
  {
    id: 'arena_vulcao_erupcao',
    name: 'Caldeira Vulcânica dos Açores',
    description: 'Crateras fumegantes e lagoas de esmeralda rodeadas pela névoa mística do arquipélago.',
    meaning: 'O poder primal da terra que ergueu as nove ilhas atlânticas do manto oceânico.',
    theme: 'natureza',
    image: ARENA_IMAGES_MAP.arena_vulcao_erupcao,
    accent: '#EF4444',
    icon: '🌋',
    category: 'ilhas',
    categoryLabel: 'Ilhas & Natureza',
    rarity: 'Épica',
    price: 8500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'nature',
    effect: 'lava',
    available: true,
    order: 10,
  },
  {
    id: 'arena_vulcao_furnas',
    name: 'Geiser & Furnas Vulcânicas',
    description: 'Fumarolas ativas e caldeiras fervilhantes no coração telúrico de São Miguel.',
    meaning: 'A força geotérmica ancestral e a gastronomia única cozida pelo calor da própria terra.',
    theme: 'natureza',
    image: ARENA_IMAGES_MAP.arena_vulcao_furnas,
    accent: '#F97316',
    icon: '♨️',
    category: 'ilhas',
    categoryLabel: 'Ilhas & Natureza',
    rarity: 'Épica',
    price: 9000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'nature',
    effect: 'fire',
    available: true,
    order: 11,
  },
  {
    id: 'arena_madeira_tropical',
    name: 'Laurissilva & Levadas da Madeira',
    description: 'Floresta pré-histórica verdejante com cascatas de água pura e fetos gigantes.',
    meaning: 'Património Mundial da UNESCO e refúgio botânico único no planeta Terra.',
    theme: 'natureza',
    image: ARENA_IMAGES_MAP.arena_madeira_tropical,
    accent: '#10B981',
    icon: '🌿',
    category: 'ilhas',
    categoryLabel: 'Ilhas & Natureza',
    rarity: 'Rara',
    price: 4000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Fácil',
    environment: 'nature',
    effect: 'rain',
    available: true,
    order: 12,
  },
  {
    id: 'arena_pico_estrelas',
    name: 'Montanha do Pico Sob as Estrelas',
    description: 'O ponto mais alto de Portugal a rasgar as nuvens sob um céu noturno salpicado de galáxias.',
    meaning: 'O teto da nação com 2.351 metros de imponência vulcânica no meio do Atlântico.',
    theme: 'natureza',
    image: ARENA_IMAGES_MAP.arena_pico_estrelas,
    accent: '#6366F1',
    icon: '⭐',
    category: 'ilhas',
    categoryLabel: 'Ilhas & Natureza',
    rarity: 'Lendária',
    price: 16000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'nature',
    effect: 'stars',
    available: true,
    order: 13,
  },
  {
    id: 'arena_madeira_noite',
    name: 'Baía do Funchal — Noite Atlântica',
    description: 'O anfiteatro iluminado do Funchal com o reflexo cintilante dos cruzeiros no porto.',
    meaning: 'O espetáculo pirotécnico e o acolhimento cosmopolita da Pérola do Atlântico.',
    theme: 'cidades',
    image: ARENA_IMAGES_MAP.arena_madeira_noite,
    accent: '#A855F7',
    icon: '🎆',
    category: 'ilhas',
    categoryLabel: 'Ilhas & Natureza',
    rarity: 'Rara',
    price: 5500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Fácil',
    environment: 'ocean',
    effect: 'fireworks',
    available: true,
    order: 14,
  },
  {
    id: 'arena_pico_aurora',
    name: 'Cume Cósmico do Pico',
    description: 'Visão etérea do cume do Pico banhado por constelações brilhantes e luz zodiacal.',
    meaning: 'A comunhão perfeita entre a geografia insular e o cosmos infinito.',
    theme: 'natureza',
    image: ARENA_IMAGES_MAP.arena_pico_aurora,
    accent: '#C084FC',
    icon: '✨',
    category: 'ilhas',
    categoryLabel: 'Ilhas & Natureza',
    rarity: 'Lendária',
    price: 17500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Extremo',
    environment: 'nature',
    effect: 'stars',
    available: true,
    order: 15,
  },
  {
    id: 'arena_costa_selvagem',
    name: 'Falésias da Costa Vicentina',
    description: 'Areias douradas e escarpas agrestes banhadas pelas águas bravas do sudoeste alentejano.',
    meaning: 'A preservação intocada da linha de costa mais selvagem e pura da Europa.',
    theme: 'natureza',
    image: ARENA_IMAGES_MAP.arena_costa_selvagem,
    accent: '#0EA5E9',
    icon: '🏖️',
    category: 'ilhas',
    categoryLabel: 'Ilhas & Natureza',
    rarity: 'Comum',
    price: 2000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Fácil',
    environment: 'ocean',
    effect: 'waves',
    available: true,
    order: 16,
  },

  // ==========================================
  // 3. HISTÓRIA & ÉPOCAS (5 Arenas)
  // ==========================================
  {
    id: 'arena_portugal_medieval',
    name: 'Guimarães — Berço da Nação',
    description: 'A torre de menagem onde D. Afonso Henriques forjou a independência de Portugal.',
    meaning: 'Aqui nasceu Portugal: o solo sagrado onde começou a história do país mais antigo da Europa.',
    theme: 'historia',
    image: ARENA_IMAGES_MAP.arena_portugal_medieval,
    accent: '#D97706',
    icon: '🛡️',
    category: 'historia',
    categoryLabel: 'História & Épocas',
    rarity: 'Rara',
    price: 6000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'monument',
    effect: 'particles',
    available: true,
    order: 17,
  },
  {
    id: 'arena_era_descobrimentos',
    name: 'Rota das Naus & Astrolábio',
    description: 'Mapas antigos, cartas de marear e caravelas a singrar oceanos nunca dantes navegados.',
    meaning: 'A revolução científica e marítima que deu novos mundos ao mundo.',
    theme: 'historia',
    image: ARENA_IMAGES_MAP.arena_era_descobrimentos,
    accent: '#0284C7',
    icon: '⛵',
    category: 'historia',
    categoryLabel: 'História & Épocas',
    rarity: 'Lendária',
    price: 18000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'ocean',
    effect: 'waves',
    available: true,
    order: 18,
  },
  {
    id: 'arena_batalha_medieval',
    name: 'Campo de Aljubarrota',
    description: 'Estandartes reais ao vento, catapultas e o lendário quadrado tático de Nuno Álvares Pereira.',
    meaning: 'A afirmação definitiva da soberania portuguesa a 14 de Agosto de 1385.',
    theme: 'historia',
    image: ARENA_IMAGES_MAP.arena_batalha_medieval,
    accent: '#B45309',
    icon: '⚔️',
    category: 'historia',
    categoryLabel: 'História & Épocas',
    rarity: 'Épica',
    price: 10000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'outdoor',
    effect: 'fire',
    available: true,
    order: 19,
  },
  {
    id: 'arena_corte_portuguesa',
    name: 'Salão Nobre da Corte Real',
    description: 'Lustres de cristal, veludo escarlate e brasões de armas esculpidos em ouro de lei.',
    meaning: 'O esplendor diplomático e cultural dos reis e rainhas de Portugal.',
    theme: 'historia',
    image: ARENA_IMAGES_MAP.arena_corte_portuguesa,
    accent: '#E11D48',
    icon: '⚜️',
    category: 'historia',
    categoryLabel: 'História & Épocas',
    rarity: 'Lendária',
    price: 20000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'monument',
    effect: 'particles',
    available: true,
    order: 20,
  },
  {
    id: 'arena_mosteiro_antigo',
    name: 'Claustros dos Templários',
    description: 'Arcadas góticas e místicas de Tomar com sombras sagradas e silêncio milenar.',
    meaning: 'A ordem dos Cavaleiros de Cristo que guardou os segredos da expansão ultramarina.',
    theme: 'historia',
    image: ARENA_IMAGES_MAP.arena_mosteiro_antigo,
    accent: '#78716C',
    icon: '🗡️',
    category: 'historia',
    categoryLabel: 'História & Épocas',
    rarity: 'Rara',
    price: 4500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'monument',
    effect: 'particles',
    available: true,
    order: 21,
  },

  // ==========================================
  // 4. CULTURA & ARTES (3 Arenas)
  // ==========================================
  {
    id: 'arena_festival_portugues',
    name: 'Arraial dos Santos Populares',
    description: 'Bandeirinhas coloridas, manjericos perfumados, sardinha assada e noites de Santo António.',
    meaning: 'A alegria contagiante da maior tradição de rua e bairrismo popular de Portugal.',
    theme: 'cultura',
    image: ARENA_IMAGES_MAP.arena_festival_portugues,
    accent: '#F43F5E',
    icon: '🎉',
    category: 'cultura',
    categoryLabel: 'Cultura & Artes',
    rarity: 'Comum',
    price: 2500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Fácil',
    environment: 'outdoor',
    effect: 'particles',
    available: true,
    order: 22,
  },
  {
    id: 'arena_fado_alfama',
    name: 'Taberna de Fado Vadio em Alfama',
    description: 'Luz ténue de candeeiros, guitarra portuguesa a chorar notas e xaile negro sobre os ombros.',
    meaning: 'A alma imortal e a saudade expressas no canto património imaterial da humanidade.',
    theme: 'cultura',
    image: ARENA_IMAGES_MAP.arena_fado_alfama,
    accent: '#9333EA',
    icon: '🎸',
    category: 'cultura',
    categoryLabel: 'Cultura & Artes',
    rarity: 'Rara',
    price: 6500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'outdoor',
    effect: 'particles',
    available: true,
    order: 23,
  },
  {
    id: 'arena_teatro_nacional',
    name: 'Teatro Nacional D. Maria II',
    description: 'Camarotes forrados a ouro, cortinas de veludo e palco imponente no Rossio.',
    meaning: 'O templo maior da dramaturgia e da língua de Camões e Gil Vicente.',
    theme: 'cultura',
    image: ARENA_IMAGES_MAP.arena_teatro_nacional,
    accent: '#EC4899',
    icon: '🎭',
    category: 'cultura',
    categoryLabel: 'Cultura & Artes',
    rarity: 'Épica',
    price: 11000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'monument',
    effect: 'particles',
    available: true,
    order: 24,
  },

  // ==========================================
  // 5. FUTEBOL & ESTÁDIOS (5 Arenas)
  // ==========================================
  {
    id: 'arena_estadio_nacional',
    name: 'Estádio Nacional do Jamor',
    description: 'A mítica tribuna de pedra no meio da mata onde se celebra a festa da Taça de Portugal.',
    meaning: 'O santuário do futebol romântico português e palco da final europeia de 1967.',
    theme: 'futebol',
    image: ARENA_IMAGES_MAP.arena_estadio_nacional,
    accent: '#22C55E',
    icon: '🏟️',
    category: 'futebol',
    categoryLabel: 'Futebol & Estádios',
    rarity: 'Rara',
    price: 5000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Fácil',
    environment: 'stadium',
    effect: 'particles',
    available: true,
    order: 25,
  },
  {
    id: 'arena_noite_jogo',
    name: 'Dérbi Clássico Sob Tempestade',
    description: 'Relvado iluminado por holofotes potentes, chuva intensa e bancadas repletas de paixão.',
    meaning: 'A rivalidade centenária e o fervor que para o país a cada grande clássico.',
    theme: 'futebol',
    image: ARENA_IMAGES_MAP.arena_noite_jogo,
    accent: '#059669',
    icon: '🌧️',
    category: 'futebol',
    categoryLabel: 'Futebol & Estádios',
    rarity: 'Épica',
    price: 9500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'stadium',
    effect: 'rain',
    available: true,
    order: 26,
  },
  {
    id: 'arena_final_nacional',
    name: 'Grande Final de Campeões',
    description: 'Show pirotécnico, fumo colorido nas bancadas e a taça de campeão a brilhar no centro.',
    meaning: 'A consagração suprema do vencedor após uma época de glória e dedicação.',
    theme: 'futebol',
    image: ARENA_IMAGES_MAP.arena_final_nacional,
    accent: '#EAB308',
    icon: '🏆',
    category: 'futebol',
    categoryLabel: 'Futebol & Estádios',
    rarity: 'Lendária',
    price: 22000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'stadium',
    effect: 'fireworks',
    available: true,
    order: 27,
  },
  {
    id: 'arena_noite_selecao',
    name: 'Noite das Quinas — Paris 2016',
    description: 'Bandeiras de Portugal no relvado do Stade de France e o troféu Henri Delaunay erguido ao céu.',
    meaning: 'O momento mais glorioso do desporto nacional: Portugal Campeão da Europa.',
    theme: 'futebol',
    image: ARENA_IMAGES_MAP.arena_noite_selecao,
    accent: '#DC2626',
    icon: '⚽',
    category: 'futebol',
    categoryLabel: 'Futebol & Estádios',
    rarity: 'Lendária',
    price: 25000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Extremo',
    environment: 'stadium',
    effect: 'particles',
    available: true,
    order: 28,
  },
  {
    id: 'arena_duelo_1v1_oficial',
    name: 'Coliseu Oficial de Duelos 1v1',
    description: 'Arena desportiva compacta e eletrificada concebida exclusivamente para confrontos diretos.',
    meaning: 'O palco supremo do frente a frente onde só o conhecimento e a rapidez vencem.',
    theme: 'futebol',
    image: ARENA_IMAGES_MAP.arena_duelo_1v1_oficial,
    accent: '#8B5CF6',
    icon: '⚔️',
    category: 'futebol',
    categoryLabel: 'Futebol & Estádios',
    rarity: 'Mítica',
    price: 30000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Lendário',
    environment: 'stadium',
    effect: 'lightning',
    available: true,
    order: 29,
  },

  // ==========================================
  // 6. FUTURISTAS & CYBERPUNK (6 Arenas)
  // ==========================================
  {
    id: 'arena_ponte_2077',
    name: 'Ponte do Infinito 2077',
    description: 'Cabos de néon azul ciano sobre o Tejo futurista com carros voadores em tráfego supersónico.',
    meaning: 'A visão arrojada de um Portugal hipertecnológico liderando o novo milénio.',
    theme: 'futuro',
    image: ARENA_IMAGES_MAP.arena_ponte_2077,
    accent: '#06B6D4',
    icon: '🚀',
    category: 'futuristas',
    categoryLabel: 'Futuristas & Cyberpunk',
    rarity: 'Épica',
    price: 12500,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'sci-fi',
    effect: 'lightning',
    available: true,
    order: 30,
  },
  {
    id: 'arena_lisboa_cybercore',
    name: 'Lisboa Cybercore 2088',
    description: 'Arranha-céus vertiginosos com hologramas da bandeira nacional e ruelas de néon rosa e roxo.',
    meaning: 'A fusão entre a calçada portuguesa e a inteligência quântica do futuro.',
    theme: 'futuro',
    image: ARENA_IMAGES_MAP.arena_lisboa_cybercore,
    accent: '#EC4899',
    icon: '🏙️',
    category: 'futuristas',
    categoryLabel: 'Futuristas & Cyberpunk',
    rarity: 'Lendária',
    price: 21000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'sci-fi',
    effect: 'particles',
    available: true,
    order: 31,
  },
  {
    id: 'arena_estacao_orbital',
    name: 'Estação Espacial Sagres',
    description: 'Módulo orbital com vista para a Península Ibérica iluminada na escuridão do espaço.',
    meaning: 'Os novos descobrimentos no espaço profundo impulsionados pela audácia lusa.',
    theme: 'futuro',
    image: ARENA_IMAGES_MAP.arena_estacao_orbital,
    accent: '#3B82F6',
    icon: '🛰️',
    category: 'futuristas',
    categoryLabel: 'Futuristas & Cyberpunk',
    rarity: 'Lendária',
    price: 24000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'sci-fi',
    effect: 'stars',
    available: true,
    order: 32,
  },
  {
    id: 'arena_portal_galactico',
    name: 'Vórtice Quântico das Quinas',
    description: 'Portal de energia interdimensional a pulsar no centro de um templo cósmico.',
    meaning: 'A ponte dimensional que une a herança histórica aos mundos do além.',
    theme: 'futuro',
    image: ARENA_IMAGES_MAP.arena_portal_galactico,
    accent: '#8B5CF6',
    icon: '🌀',
    category: 'futuristas',
    categoryLabel: 'Futuristas & Cyberpunk',
    rarity: 'Mítica',
    price: 35000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Extremo',
    environment: 'sci-fi',
    effect: 'particles',
    available: true,
    order: 33,
  },
  {
    id: 'arena_cyber_laboratorio',
    name: 'Complexo Quântico Nanotech',
    description: 'Laboratório de computação de ponta e reatores de fusão limpa em solo português.',
    meaning: 'A vanguarda científica nacional impulsionando a inovação aeroespacial.',
    theme: 'futuro',
    image: ARENA_IMAGES_MAP.arena_cyber_laboratorio,
    accent: '#14B8A6',
    icon: '🔬',
    category: 'futuristas',
    categoryLabel: 'Futuristas & Cyberpunk',
    rarity: 'Épica',
    price: 13000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Médio',
    environment: 'sci-fi',
    effect: 'lightning',
    available: true,
    order: 34,
  },
  {
    id: 'arena_megalopolis_lusa',
    name: 'Metrópole Atlântica 2100',
    description: 'Cúpulas energéticas e vias magnéticas que cruzam o país de norte a sul em minutos.',
    meaning: 'O futuro hiperconectado e sustentável do território nacional.',
    theme: 'futuro',
    image: ARENA_IMAGES_MAP.arena_megalopolis_lusa,
    accent: '#F43F5E',
    icon: '⚡',
    category: 'futuristas',
    categoryLabel: 'Futuristas & Cyberpunk',
    rarity: 'Mítica',
    price: 38000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Lendário',
    environment: 'sci-fi',
    effect: 'lightning',
    available: true,
    order: 35,
  },

  // ==========================================
  // 7. MODO MALUCO (5 Arenas)
  // ==========================================
  {
    id: 'arena_portugal_ao_contrario',
    name: 'Portugal ao Contrário',
    description: 'As caravelas navegam nas nuvens, os castelos flutuam e a gravidade está totalmente invertida.',
    meaning: 'O teste supremo de reflexos onde nada obedece às leis normais da física.',
    theme: 'maluco',
    image: ARENA_IMAGES_MAP.arena_portugal_ao_contrario,
    accent: '#F59E0B',
    icon: '🙃',
    category: 'maluco',
    categoryLabel: 'Modo Maluco',
    rarity: 'Épica',
    price: 12000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'fantasy',
    effect: 'particles',
    available: true,
    order: 36,
  },
  {
    id: 'arena_caos_patos',
    name: 'Invasão dos Patos de Aveiro',
    description: 'Patos colossais de borracha amarela a navegar pelos canais da Ria e a bloquear moliceiros.',
    meaning: 'O humor e a loucura criativa do modo mais divertido do Acorda Portugal.',
    theme: 'maluco',
    image: ARENA_IMAGES_MAP.arena_caos_patos,
    accent: '#FACC15',
    icon: '🦆',
    category: 'maluco',
    categoryLabel: 'Modo Maluco',
    rarity: 'Rara',
    price: 7000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Fácil',
    environment: 'fantasy',
    effect: 'waves',
    available: true,
    order: 37,
  },
  {
    id: 'arena_dentro_cerebro',
    name: 'Tempestade de Sinapses Neurais',
    description: 'Descargas elétricas entre neurónios dourados no interior da mente de um génio do quiz.',
    meaning: 'A visualização visual do raciocínio ultra-rápido no momento da resposta perfeita.',
    theme: 'maluco',
    image: ARENA_IMAGES_MAP.arena_dentro_cerebro,
    accent: '#E11D48',
    icon: '🧠',
    category: 'maluco',
    categoryLabel: 'Modo Maluco',
    rarity: 'Lendária',
    price: 23000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Extremo',
    environment: 'fantasy',
    effect: 'lightning',
    available: true,
    order: 38,
  },
  {
    id: 'arena_dimensao_psicadelica',
    name: 'Dimensão Fractal Lusitana',
    description: 'Padrões geométricos em espiral caleidoscópica desafiando a percepção visual do jogador.',
    meaning: 'A vertigem do desafio mental levado ao limite absoluto.',
    theme: 'maluco',
    image: ARENA_IMAGES_MAP.arena_dimensao_psicadelica,
    accent: '#A855F7',
    icon: '🔮',
    category: 'maluco',
    categoryLabel: 'Modo Maluco',
    rarity: 'Épica',
    price: 14000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Difícil',
    environment: 'fantasy',
    effect: 'particles',
    available: true,
    order: 39,
  },
  {
    id: 'arena_labirinto_onirico',
    name: 'Labirinto das Ilusões',
    description: 'Corredores infinitos de espelhos e caminhos mutantes onde a lógica se dissolve.',
    meaning: 'A capacidade de encontrar a resposta certa no meio do puro caos visual.',
    theme: 'maluco',
    image: ARENA_IMAGES_MAP.arena_labirinto_onirico,
    accent: '#EC4899',
    icon: '🌀',
    category: 'maluco',
    categoryLabel: 'Modo Maluco',
    rarity: 'Lendária',
    price: 26000,
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Extremo',
    environment: 'fantasy',
    effect: 'particles',
    available: true,
    order: 40,
  },

  // ==========================================
  // 8. 👑 ULTRA-EXCLUSIVAS / MÉRITO (3 Arenas)
  // ==========================================
  {
    id: 'arena_excl_campeao',
    name: 'Trono Sagrado do Campeão Nacional',
    description: 'O trono régio forjado em ouro e platina, reservado ao Número 1 do Ranking de Portugal.',
    meaning: 'A distinção máxima do Acorda Portugal para quem domina sem rival a sabedoria nacional.',
    theme: 'exclusivo',
    image: ARENA_IMAGES_MAP.arena_excl_campeao,
    accent: '#F59E0B',
    icon: '👑',
    category: 'exclusivas',
    categoryLabel: '👑 Ultra-Exclusivas',
    rarity: 'Exclusiva',
    price: null,
    unlockCondition: 'Alcançar o 1º Lugar no Ranking Nacional',
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Lendário',
    environment: 'monument',
    effect: 'fireworks',
    available: true,
    order: 41,
  },
  {
    id: 'arena_excl_fundadores',
    name: 'Monumento Perpétuo dos Fundadores',
    description: 'O panteão eterno talhado na rocha das eras, reservado aos pioneiros da versão 1.0.0.',
    meaning: 'Homenagem eterna aos jogadores que acreditaram e construíram o projeto desde o primeiro dia.',
    theme: 'exclusivo',
    image: ARENA_IMAGES_MAP.arena_excl_fundadores,
    accent: '#3B82F6',
    icon: '🏛️',
    category: 'exclusivas',
    categoryLabel: '👑 Ultra-Exclusivas',
    rarity: 'Exclusiva',
    price: null,
    unlockCondition: 'Passe Fundador ou Nível 50 de Conta',
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Lendário',
    environment: 'monument',
    effect: 'particles',
    available: true,
    order: 42,
  },
  {
    id: 'arena_excl_lenda_100',
    name: 'Coliseu dos Imortais — 100 Vitórias',
    description: 'A arena sagrada banhada a fogo vivo onde os mestres dos duelos consagram a sua lenda.',
    meaning: 'Recompensa de prestígio supremo atribuída aos gladiadores com 100 vitórias em duelo 1v1.',
    theme: 'exclusivo',
    image: ARENA_IMAGES_MAP.arena_excl_lenda_100,
    accent: '#EF4444',
    icon: '🔥',
    category: 'exclusivas',
    categoryLabel: '👑 Ultra-Exclusivas',
    rarity: 'Exclusiva',
    price: null,
    unlockCondition: 'Vencer 100 Duelos Multiplayer 1v1',
    unlockedByDefault: false,
    unlocked: false,
    difficulty: 'Lendário',
    environment: 'stadium',
    effect: 'fire',
    available: true,
    order: 43,
  },
]

function generateCatalogFile() {
  const filePath = path.join(process.cwd(), 'src', 'data', 'shopArenas.ts')
  const arenasDir = path.join(process.cwd(), 'public', 'arenas')

  // Validar correspondência 1:1 física
  const physicalFiles = fs.readdirSync(arenasDir)
  const imagePaths = new Set<string>()

  CATALOG_43.forEach(arena => {
    const filename = path.basename(arena.image)
    if (!fs.existsSync(path.join(arenasDir, filename))) {
      throw new Error(`Ficheiro não encontrado para a arena ${arena.id}: ${filename}`)
    }
    if (imagePaths.has(arena.image)) {
      throw new Error(`Imagem duplicada no catálogo: ${arena.image}`)
    }
    imagePaths.add(arena.image)
  })

  if (physicalFiles.length !== 43) {
    throw new Error(`Esperados 43 ficheiros em public/arenas, encontrados: ${physicalFiles.length}`)
  }

  const fileContent = `import type {
  ArenaDefinition,
  Arena,
  ArenaItem,
  ArenaRarity,
  ArenaEffect,
  ArenaCategory,
} from '@/src/types/arena'

export type { ArenaDefinition, Arena, ArenaItem, ArenaRarity, ArenaEffect, ArenaCategory }

/**
 * MAPEAMENTO EXPLÍCITO E OFICIAL DAS 43 IMAGENS DE ARENAS (1:1 BIJEÇÃO)
 */
export const ARENA_IMAGES = ${JSON.stringify(ARENA_IMAGES_MAP, null, 2)} as const

export type ArenaImageKey = keyof typeof ARENA_IMAGES

export function getOfficialArenaImage(arenaId: string): string {
  const normalizedId = String(arenaId).toLowerCase().trim()
  if (normalizedId in ARENA_IMAGES) {
    return ARENA_IMAGES[normalizedId as ArenaImageKey]
  }
  const match = ARENA_SHOP_CATALOG.find((a) => a.id.toLowerCase() === normalizedId)
  if (match) return match.image
  return ARENA_SHOP_CATALOG[0].image
}

export const getArenaRarityBadge = (rarity: ArenaRarity): string => {
  switch (rarity) {
    case 'Comum':
      return 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
    case 'Rara':
      return 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40'
    case 'Épica':
      return 'bg-purple-500/20 text-purple-300 border-purple-500/40'
    case 'Lendária':
      return 'bg-amber-500/20 text-amber-300 border-amber-500/40 shadow-[0_0_10px_rgba(245,158,11,0.25)]'
    case 'Mítica':
      return 'bg-rose-500/20 text-rose-300 border-rose-500/50 shadow-[0_0_12px_rgba(244,63,94,0.35)]'
    case 'Exclusiva':
      return 'bg-rose-600/30 text-rose-200 border-rose-400/60 shadow-[0_0_15px_rgba(244,63,94,0.5)]'
    default:
      return 'bg-slate-800 text-slate-300 border-slate-700'
  }
}

export const ARENA_CATEGORIES_LIST = [
  { key: 'todos', label: 'Todas as Arenas', icon: '🌐' },
  { key: 'portugal', label: 'Portugal & Cidades', icon: '🇵🇹' },
  { key: 'ilhas', label: 'Ilhas & Natureza', icon: '🌋' },
  { key: 'historia', label: 'História & Épocas', icon: '⚔️' },
  { key: 'cultura', label: 'Cultura & Artes', icon: '🎭' },
  { key: 'futebol', label: 'Futebol & Estádios', icon: '⚽' },
  { key: 'futuristas', label: 'Futuristas & Cyberpunk', icon: '🚀' },
  { key: 'maluco', label: 'Modo Maluco', icon: '🤪' },
  { key: 'exclusivas', label: '👑 Ultra-Exclusivas', icon: '👑' },
] as const

export const ARENA_SHOP_CATALOG: ArenaDefinition[] = ${JSON.stringify(
    CATALOG_43.map(a => ({
      ...a,
      imagePath: a.image,
      shopImage: a.image,
      gameImage: a.image,
      gameBackground: a.image,
      duelImage: a.image,
      duelBackground: a.image,
      thumbnail: a.image,
      background: a.image,
      badgeColor: a.rarity === 'Comum'
        ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
        : a.rarity === 'Rara'
        ? 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40'
        : a.rarity === 'Épica'
        ? 'bg-purple-500/20 text-purple-300 border-purple-500/40'
        : a.rarity === 'Lendária'
        ? 'bg-amber-500/20 text-amber-300 border-amber-500/40 shadow-[0_0_10px_rgba(245,158,11,0.25)]'
        : a.rarity === 'Mítica'
        ? 'bg-rose-500/20 text-rose-300 border-rose-500/50 shadow-[0_0_12px_rgba(244,63,94,0.35)]'
        : 'bg-rose-600/30 text-rose-200 border-rose-400/60 shadow-[0_0_15px_rgba(244,63,94,0.5)]',
    })),
    null,
    2
  )}

export const FALLBACK_ARENA: ArenaDefinition = ARENA_SHOP_CATALOG[0]

export const shopArenas: ArenaDefinition[] = ARENA_SHOP_CATALOG

export function getArenaById(id: string | null | undefined): ArenaDefinition {
  if (!id) return ARENA_SHOP_CATALOG[0]
  const normalizedId = String(id).toLowerCase().trim()

  const directMatch = ARENA_SHOP_CATALOG.find(
    (a) => a.id.toLowerCase() === normalizedId,
  )
  if (directMatch) return directMatch

  // Mapeamento retrocompatível para IDs legados
  const legacyAliases: Record<string, string> = {
    'arena-1': 'arena_praca_liberdade',
    'arena-2': 'arena_castelo_obidos',
    'arena-3': 'arena_costa_atlantica',
    'arena-4': 'arena_ponte_d_luis',
    'arena-5': 'arena_lisboa_imperial',
    'arena-6': 'arena_torre_belem',
    'arena-7': 'arena_vulcao_erupcao',
    'arena-8': 'arena_madeira_tropical',
    'arena-9': 'arena_pico_estrelas',
    'arena-10': 'arena_madeira_noite',
    'arena-1v1': 'arena_duelo_1v1_oficial',
    'arena_1': 'arena_praca_liberdade',
    'arena_2': 'arena_castelo_obidos',
    'arena_3': 'arena_costa_atlantica',
    'arena_4': 'arena_ponte_d_luis',
    'arena_5': 'arena_lisboa_imperial',
    'arena_6': 'arena_torre_belem',
    'arena_7': 'arena_vulcao_erupcao',
    'arena_8': 'arena_madeira_tropical',
    'arena_9': 'arena_pico_estrelas',
    'arena_10': 'arena_madeira_noite',
    'estadio-nacional': 'arena_estadio_nacional',
    'batalha-medieval': 'arena_batalha_medieval',
    'castelo-obidos': 'arena_castelo_obidos',
    'praca-liberdade': 'arena_praca_liberdade',
    'ponte-d-luis': 'arena_ponte_d_luis',
    'torre-belem': 'arena_torre_belem',
    'vulcao-acores': 'arena_vulcao_erupcao',
  }

  const aliasTarget = legacyAliases[normalizedId]
  if (aliasTarget) {
    const aliasedMatch = ARENA_SHOP_CATALOG.find((a) => a.id === aliasTarget)
    if (aliasedMatch) return aliasedMatch
  }

  return ARENA_SHOP_CATALOG[0]
}

export function getDefaultArena(): ArenaDefinition {
  return ARENA_SHOP_CATALOG[0]
}

export function getRandomArena(): ArenaDefinition {
  const randomIndex = Math.floor(Math.random() * ARENA_SHOP_CATALOG.length)
  return ARENA_SHOP_CATALOG[randomIndex] || ARENA_SHOP_CATALOG[0]
}
`

  fs.writeFileSync(filePath, fileContent, 'utf-8')
  console.log(`✅ Catálogo gerado com sucesso com ${CATALOG_43.length} arenas e ARENA_IMAGES!`)
}

generateCatalogFile()
