import fs from 'fs'
import path from 'path'

const filePath = path.resolve(process.cwd(), 'src/data/vipCatalog.ts')
let content = fs.readFileSync(filePath, 'utf-8')

const replacements: [RegExp, string][] = [
  // Signature
  [
    /name: 'Soberano de Ourique',[\s\S]*?assetPath: '\/images\/avatars\/vip\/signature\/soberano-ourique\.webp',[\s\S]*?thumbnailPath: '\/images\/avatars\/vip\/signature\/soberano-ourique\.webp',[\s\S]*?previewPath: '\/images\/avatars\/vip\/signature\/soberano-ourique\.webp',/,
    `name: 'Imperador Lusitano',
    tier: 1,
    tierName: 'Signature VIP',
    storeSection: 'signature',
    category: 'avatar',
    rarity: 'Mythic',
    rarityBadge: 'COLECIONADOR MÍTICO',
    prestigeTier: 'MÍTICO',
    profileBannerTag: 'ED. LIMITADA',
    priceEUR: 29.99,
    priceCents: 2999,
    currency: 'EUR',
    isLimited: true,
    limitedUnits: 100,
    stock: 100,
    serialised: true,
    description: 'A identidade suprema: a linhagem dos reis que ergueram a pátria independente em 1143.',
    visualConcept: 'Monarca imperial envolto em manto carmesim com quinas bordadas a ouro, coroa das cortes e aura luminescente.',
    animation: 'Manto ondulante, aura dourada de entrada e partículas cintilantes.',
    effect: 'Aura imperial e brasão das quinas iluminam o duelo.',
    visualEffectsList: [
      'Aura dourada de entrada',
      'Partículas das quinas portuguesas',
      'Brilho pulsante no escudo',
      'Manto animado em movimento',
    ],
    lobbyAnimation: 'Manto ondulante com halo dourado subtil',
    duelIntroSound: 'fanfarra-real',
    profileBadge: 'IMPERADOR',
    bundleDescription: 'Avatar exclusivo + animação de entrada + pose de vitória + badge de perfil.',
    assetPath: '/images/avatars/vip/signature/imperador-lusitano.webp',
    thumbnailPath: '/images/avatars/vip/signature/imperador-lusitano.webp',
    previewPath: '/images/avatars/vip/signature/imperador-lusitano.webp',`
  ],
  [
    /name: 'Dragão de Viriato',[\s\S]*?assetPath: '\/images\/avatars\/vip\/signature\/dragao-viriato\.webp',[\s\S]*?thumbnailPath: '\/images\/avatars\/vip\/signature\/dragao-viriato\.webp',[\s\S]*?previewPath: '\/images\/avatars\/vip\/signature\/dragao-viriato\.webp',/,
    `name: 'Dragão de Portugal',
    tier: 1,
    tierName: 'Signature VIP',
    storeSection: 'signature',
    category: 'avatar',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 24.99,
    priceCents: 2499,
    currency: 'EUR',
    description: 'O espírito indomável do dragão heráldico português com armadura de ferro e escamas reluzentes.',
    visualConcept: 'Guerreiro lusitano com armadura de ferro e motivos draconianos, escamas reluzentes e olhos de fogo ancestral.',
    animation: 'Fumo subtil a emergir dos ombros e movimento das escamas na entrada do duelo.',
    effect: 'Chamas draconianas surgem no chão ao entrar em duelo, evaporando lentamente.',
    visualEffectsList: [
      'Chamas draconianas de entrada',
      'Fumo subtil nos ombros',
      'Escamas animadas em movimento',
      'Olhos incandescentes no perfil',
    ],
    lobbyAnimation: 'Fumo discreto com brilho de brasa',
    profileBadge: 'DRAGÃO',
    bundleDescription: 'Avatar exclusivo + animação de entrada + animação de vitória + badge.',
    assetPath: '/images/avatars/vip/signature/dragao-portugal.webp',
    thumbnailPath: '/images/avatars/vip/signature/dragao-portugal.webp',
    previewPath: '/images/avatars/vip/signature/dragao-portugal.webp',`
  ],
  [
    /name: 'Navegador dos Descobrimentos',[\s\S]*?assetPath: '\/images\/avatars\/vip\/signature\/navegador-descobrimentos\.webp',[\s\S]*?thumbnailPath: '\/images\/avatars\/vip\/signature\/navegador-descobrimentos\.webp',[\s\S]*?previewPath: '\/images\/avatars\/vip\/signature\/navegador-descobrimentos\.webp',/,
    `name: 'Navegador Eterno',
    tier: 1,
    tierName: 'Signature VIP',
    storeSection: 'signature',
    category: 'avatar',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 14.99,
    priceCents: 1499,
    currency: 'EUR',
    description: 'O explorador dos mares que levou Portugal ao limite do mundo conhecido.',
    visualConcept: 'Capitão explorador da era dos Descobrimentos com vestes cerimoniais e astrolábio cintilante.',
    animation: 'O astrolábio roda lentamente; o manto move-se ao ritmo do vento atlântico.',
    effect: 'Efeito de bússola oceânica surge em torno do avatar na apresentação do duelo.',
    visualEffectsList: [
      'Bússola animada em rotação',
      'Manto atlântico flutuante',
      'Astrolábio cintilante',
      'Estrelas de navegação subtis',
    ],
    lobbyAnimation: 'Astrolábio em rotação subtil com brilho de estrela',
    profileBadge: 'NAVEGADOR',
    bundleDescription: 'Avatar exclusivo + entrada animada + badge.',
    assetPath: '/images/avatars/vip/signature/navegador-eterno.webp',
    thumbnailPath: '/images/avatars/vip/signature/navegador-eterno.webp',
    previewPath: '/images/avatars/vip/signature/navegador-eterno.webp',`
  ],
  [
    /name: 'Guardião das Quinas',[\s\S]*?assetPath: '\/images\/avatars\/vip\/signature\/guardiao-quinas\.webp',[\s\S]*?thumbnailPath: '\/images\/avatars\/vip\/signature\/guardiao-quinas\.webp',[\s\S]*?previewPath: '\/images\/avatars\/vip\/signature\/guardiao-quinas\.webp',/,
    `name: 'Guardião da Nação',
    tier: 1,
    tierName: 'Signature VIP',
    storeSection: 'signature',
    category: 'avatar',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 9.99,
    priceCents: 999,
    currency: 'EUR',
    description: 'O protetor da nação, armado com o escudo das cinco quinas e o juramento de defender Portugal.',
    visualConcept: 'Paladino de elite com armadura monumental, escudo com as quinas de Portugal em relevo.',
    animation: 'O escudo ergue-se subtilmente em repouso; a armadura reflete luz dinâmica.',
    effect: 'Anel de energia defensiva manifesta-se durante a apresentação do duelo.',
    visualEffectsList: [
      'Anel de energia defensiva',
      'Escudo animado com quinas',
      'Reflexos de luz na armadura',
    ],
    lobbyAnimation: 'Escudo com pulso de energia subtil',
    profileBadge: 'GUARDIÃO',
    bundleDescription: 'Avatar exclusivo + animação de entrada + badge.',
    assetPath: '/images/avatars/vip/signature/guardiao-nacao.webp',
    thumbnailPath: '/images/avatars/vip/signature/guardiao-nacao.webp',
    previewPath: '/images/avatars/vip/signature/guardiao-nacao.webp',`
  ],

  // Arenas
  [
    /name: 'Trono do Primeiro Reino',[\s\S]*?assetPath: '\/arenas\/vip\/ultimate\/trono-primeiro-reino\.webp',[\s\S]*?thumbnailPath: '\/arenas\/vip\/ultimate\/trono-primeiro-reino\.webp',[\s\S]*?previewPath: '\/arenas\/vip\/ultimate\/trono-primeiro-reino\.webp',/,
    `name: 'Trono Supremo do Campeão',
    tier: 2,
    tierName: 'Arenas Históricas',
    storeSection: 'arenas',
    category: 'arena',
    rarity: 'Mythic',
    rarityBadge: 'COLECIONADOR MÍTICO',
    prestigeTier: 'MÍTICO',
    profileBannerTag: 'ED. LIMITADA',
    priceEUR: 39.99,
    priceCents: 3999,
    currency: 'EUR',
    isLimited: true,
    limitedUnits: 50,
    stock: 50,
    serialised: true,
    description: 'A arena suprema do Acorda Portugal: o trono onde o campeão nacional reina sobre o universo 2150.',
    visualConcept: 'Trono colossal de ouro e platina, pilares de fogo e auréola volumétrica de campeão nacional.',
    animation: 'Estandartes reais esvoaçando, partículas atmosféricas douradas e entrada cinematográfica.',
    effect: 'O lado vencedor recebe um holofote dourado real no encerramento do duelo.',
    visualEffectsList: [
      'Holofote dourado de vitória',
      'Estandartes animados esvoaçando',
      'Partículas douradas atmosféricas',
      'Fanfarra real na entrada',
      'Iluminação dinâmica do trono',
    ],
    lobbyAnimation: 'Partículas douradas com halo real',
    duelIntroSound: 'trompete-real-primeiro-reino',
    profileBadge: 'TRONO SUPREMO',
    bundleDescription: 'Arena exclusiva + sequência cinematográfica + efeito de vitória + badge numerado.',
    assetPath: '/arenas/vip/ultimate/trono-supremo-campeao.webp',
    thumbnailPath: '/arenas/vip/ultimate/trono-supremo-campeao.webp',
    previewPath: '/arenas/vip/ultimate/trono-supremo-campeao.webp',`
  ],
  [
    /name: 'Palácio dos Descobrimentos',[\s\S]*?assetPath: '\/arenas\/vip\/ultimate\/palacio-descobrimentos\.webp',[\s\S]*?thumbnailPath: '\/arenas\/vip\/ultimate\/palacio-descobrimentos\.webp',[\s\S]*?previewPath: '\/arenas\/vip\/ultimate\/palacio-descobrimentos\.webp',/,
    `name: 'Portugal Celestial',
    tier: 2,
    tierName: 'Arenas Históricas',
    storeSection: 'arenas',
    category: 'arena',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 24.99,
    priceCents: 2499,
    currency: 'EUR',
    description: 'Portugal 3D em escala monumental flutuando no espaço sideral com nebulosas cósmicas.',
    visualConcept: 'O território nacional transcende a Terra e brilha no cosmos cercado de constelações.',
    animation: 'Nebulosa em espiral, chuva de meteoros dourados e órbita estelar.',
    effect: 'Explosão de supernova cósmica com partículas estelares.',
    visualEffectsList: [
      'Explosão de luz estelar na vitória',
      'Nebulosa cósmica animada',
      'Relevo 3D de Portugal flutuante',
      'Satélites orbitais em transmissão',
    ],
    bundleDescription: 'Arena + entrada estelar + efeito cósmico.',
    assetPath: '/arenas/vip/ultimate/portugal-celestial.webp',
    thumbnailPath: '/arenas/vip/ultimate/portugal-celestial.webp',
    previewPath: '/arenas/vip/ultimate/portugal-celestial.webp',`
  ],
  [
    /name: 'Campo de Aljubarrota',[\s\S]*?assetPath: '\/arenas\/vip\/ultimate\/campo-aljubarrota\.webp',[\s\S]*?thumbnailPath: '\/arenas\/vip\/ultimate\/campo-aljubarrota\.webp',[\s\S]*?previewPath: '\/arenas\/vip\/ultimate\/campo-aljubarrota\.webp',/,
    `name: 'Coliseu dos Campeões',
    tier: 2,
    tierName: 'Arenas Históricas',
    storeSection: 'arenas',
    category: 'arena',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 19.99,
    priceCents: 1999,
    currency: 'EUR',
    description: 'Coliseu circular futurista com bancadas em camadas, feixes de luz vertical e estandartes dos 20 distritos.',
    visualConcept: 'Arena de gladiadores intelectuais com chão de vidro temperado e iluminação inferior dramática.',
    animation: 'Feixes de luz vertical, pirotecnia de combate e canhões de chama.',
    effect: 'Vitória ativa pirotecnia de campeão e ovação monumental.',
    visualEffectsList: [
      'Canhões de chama a cada acerto',
      'Bancadas monumentais iluminadas',
      '20 Estandartes distritais flutuantes',
      'Pirotecnia de vitória',
    ],
    bundleDescription: 'Arena + efeito de vitória épico.',
    assetPath: '/arenas/vip/ultimate/coliseu-campeoes.webp',
    thumbnailPath: '/arenas/vip/ultimate/coliseu-campeoes.webp',
    previewPath: '/arenas/vip/ultimate/coliseu-campeoes.webp',`
  ],
  [
    /name: 'Castelo de Guimarães',[\s\S]*?assetPath: '\/arenas\/vip\/ultimate\/castelo-guimaraes\.webp',[\s\S]*?thumbnailPath: '\/arenas\/vip\/ultimate\/castelo-guimaraes\.webp',[\s\S]*?previewPath: '\/arenas\/vip\/ultimate\/castelo-guimaraes\.webp',/,
    `name: 'Palácio dos Reis',
    tier: 2,
    tierName: 'Arenas Históricas',
    storeSection: 'arenas',
    category: 'arena',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 16.99,
    priceCents: 1699,
    currency: 'EUR',
    description: 'Salão nobre com arcadas manuelinas de filigrana entrelaçada e vitrais cibernéticos luminosos.',
    visualConcept: 'A arte de Quinhentos renascida na era digital mais avançada com candelabros de cristal flutuantes.',
    animation: 'Vitrais de plasma multicolorido com pulsos luminescentes.',
    effect: 'Iluminação de vitrais manuelinos projeta cores históricas na partida.',
    visualEffectsList: [
      'Vitrais com pulsos de luz',
      'Arcadas manuelinas iluminadas',
      'Candelabros flutuantes',
    ],
    bundleDescription: 'Arena + animação de vitrais manuelinos.',
    assetPath: '/arenas/vip/ultimate/palacio-reis.webp',
    thumbnailPath: '/arenas/vip/ultimate/palacio-reis.webp',
    previewPath: '/arenas/vip/ultimate/palacio-reis.webp',`
  ],
  [
    /name: 'Muralhas do Além-Tejo',[\s\S]*?assetPath: '\/arenas\/vip\/ultimate\/muralhas-alem-tejo\.webp',[\s\S]*?thumbnailPath: '\/arenas\/vip\/ultimate\/muralhas-alem-tejo\.webp',[\s\S]*?previewPath: '\/arenas\/vip\/ultimate\/muralhas-alem-tejo\.webp',/,
    `name: 'Cidadela Eterna',
    tier: 2,
    tierName: 'Arenas Históricas',
    storeSection: 'arenas',
    category: 'arena',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 12.99,
    priceCents: 1299,
    currency: 'EUR',
    description: 'Cidadela fortificada no pico da Serra da Estrela, rodeada por névoa gelada e muralhas eternas.',
    visualConcept: 'No topo das serras mais altas, a fortaleza inexpugnável que nunca conheceu a derrota.',
    animation: 'Tochas azuis nas muralhas e vento suave de montanha.',
    effect: 'Névoa alpina dissipa-se ao iniciar o combate.',
    visualEffectsList: [
      'Névoa alpina animada',
      'Tochas azuis nas muralhas',
      'Céu alpino estrelado',
    ],
    bundleDescription: 'Arena + efeito de fortaleza de montanha.',
    assetPath: '/arenas/vip/ultimate/cidadela-eterna.webp',
    thumbnailPath: '/arenas/vip/ultimate/cidadela-eterna.webp',
    previewPath: '/arenas/vip/ultimate/cidadela-eterna.webp',`
  ],

  // Frames
  [
    /name: 'Ordem de Cristo',[\s\S]*?assetPath: '\/images\/frames\/vip\/ordem-de-cristo\.webp',[\s\S]*?thumbnailPath: '\/images\/frames\/vip\/ordem-de-cristo\.webp',[\s\S]*?previewPath: '\/images\/frames\/vip\/ordem-de-cristo\.webp',/,
    `name: 'Coroa do Império',
    tier: 3,
    tierName: 'Molduras Reais',
    storeSection: 'identities',
    category: 'frame',
    rarity: 'Mythic',
    rarityBadge: 'COLECIONADOR MÍTICO',
    prestigeTier: 'MÍTICO',
    profileBannerTag: 'ED. LIMITADA',
    priceEUR: 29.99,
    priceCents: 2999,
    currency: 'EUR',
    isLimited: true,
    limitedUnits: 200,
    stock: 200,
    serialised: true,
    description: 'A coroa monumental do império forjada a ouro puro com rubis e esmeraldas.',
    visualConcept: 'Coroa real em ouro maciço com pedras preciosas e brilho imperial.',
    animation: 'A coroa orbita com partículas solares douradas.',
    effect: 'Pulsar dourado da coroa ilumina o avatar.',
    visualEffectsList: [
      'Partículas solares douradas',
      'Brilho no centro da coroa',
      'Halo tridimensional',
    ],
    bundleDescription: 'Moldura animada + brilho de perfil + badge.',
    assetPath: '/images/frames/vip/coroa-imperio.webp',
    thumbnailPath: '/images/frames/vip/coroa-imperio.webp',
    previewPath: '/images/frames/vip/coroa-imperio.webp',`
  ],
  [
    /name: 'Quinas Reais de Portugal',[\s\S]*?assetPath: '\/images\/frames\/vip\/quinas-reais-portugal\.webp',[\s\S]*?thumbnailPath: '\/images\/frames\/vip\/quinas-reais-portugal\.webp',[\s\S]*?previewPath: '\/images\/frames\/vip\/quinas-reais-portugal\.webp',/,
    `name: 'Diamante Lusitano',
    tier: 3,
    tierName: 'Molduras Reais',
    storeSection: 'identities',
    category: 'frame',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 19.99,
    priceCents: 1999,
    currency: 'EUR',
    description: 'Moldura geométrica lapidada em diamante puro com reflexos prismáticos de luz.',
    visualConcept: 'Faceta de diamante puro com reflexos das quinas e luz brilhante.',
    animation: 'Reflexos de luz prismática percorrem a moldura.',
    effect: 'Brilho de cristal a cada vitória.',
    visualEffectsList: [
      'Reflexos de luz prismática',
      'Brilho cristalino pulsante',
    ],
    bundleDescription: 'Moldura + efeito prismático.',
    assetPath: '/images/frames/vip/diamante-lusitano.webp',
    thumbnailPath: '/images/frames/vip/diamante-lusitano.webp',
    previewPath: '/images/frames/vip/diamante-lusitano.webp',`
  ],
  [
    /name: 'Constelação dos Navegadores',[\s\S]*?assetPath: '\/images\/frames\/vip\/constelacao-navegadores\.webp',[\s\S]*?thumbnailPath: '\/images\/frames\/vip\/constelacao-navegadores\.webp',[\s\S]*?previewPath: '\/images\/frames\/vip\/constelacao-navegadores\.webp',/,
    `name: 'Fogo do Campeão',
    tier: 3,
    tierName: 'Molduras Reais',
    storeSection: 'identities',
    category: 'frame',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 16.99,
    priceCents: 1699,
    currency: 'EUR',
    description: 'Chamas vivas de glória que ardem sem cessar ao redor da fotografia do campeão.',
    visualConcept: 'Labaredas ardentes e brasas em ascensão.',
    animation: 'Chamas dinâmicas a arder com brasas ascendentes.',
    effect: 'Labaredas de vitória.',
    visualEffectsList: [
      'Chamas vivas animadas',
      'Brasas ascendentes',
    ],
    bundleDescription: 'Moldura ardente de campeão.',
    assetPath: '/images/frames/vip/fogo-campeao.webp',
    thumbnailPath: '/images/frames/vip/fogo-campeao.webp',
    previewPath: '/images/frames/vip/fogo-campeao.webp',`
  ],
  [
    /name: 'Azulejo Dourado Manuelino',[\s\S]*?assetPath: '\/images\/frames\/vip\/azulejo-dourado\.webp',[\s\S]*?thumbnailPath: '\/images\/frames\/vip\/azulejo-dourado\.webp',[\s\S]*?previewPath: '\/images\/frames\/vip\/azulejo-dourado\.webp',/,
    `name: 'Portugal Ouro',
    tier: 3,
    tierName: 'Molduras Reais',
    storeSection: 'identities',
    category: 'frame',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 12.99,
    priceCents: 1299,
    currency: 'EUR',
    description: 'Moldura de ouro nobre inspirada na filigrana e símbolos patrióticos portugueses.',
    visualConcept: 'Ouro trabalhado com filigrana e padrões nacionais.',
    animation: 'Brilho de ouro suave contínuo.',
    effect: 'Aura dourada no perfil.',
    visualEffectsList: [
      'Filigrana dourada',
      'Brilho suave',
    ],
    bundleDescription: 'Moldura de ouro nobre.',
    assetPath: '/images/frames/vip/portugal-ouro.webp',
    thumbnailPath: '/images/frames/vip/portugal-ouro.webp',
    previewPath: '/images/frames/vip/portugal-ouro.webp',`
  ],
  [
    /name: 'Calçada da Glória',[\s\S]*?assetPath: '\/images\/frames\/vip\/calcada-gloria\.webp',[\s\S]*?thumbnailPath: '\/images\/frames\/vip\/calcada-gloria\.webp',[\s\S]*?previewPath: '\/images\/frames\/vip\/calcada-gloria\.webp',/,
    `name: 'Trono Celestial',
    tier: 3,
    tierName: 'Molduras Reais',
    storeSection: 'identities',
    category: 'frame',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 9.99,
    priceCents: 999,
    currency: 'EUR',
    description: 'Moldura celestial translúcida com partículas astrais de alta resolução.',
    visualConcept: 'Cristal etéreo translúcido com energia cósmica.',
    animation: 'Partículas astrais em rotação.',
    effect: 'Aura celeste suave.',
    visualEffectsList: [
      'Cristal translúcido',
      'Partículas celestes',
    ],
    bundleDescription: 'Moldura celestial etérea.',
    assetPath: '/images/frames/vip/trono-celestial.webp',
    thumbnailPath: '/images/frames/vip/trono-celestial.webp',
    previewPath: '/images/frames/vip/trono-celestial.webp',`
  ],

  // Titles
  [
    /name: '«Imperador de Portugal»',[\s\S]*?assetPath: '\/images\/titles\/vip\/imperador-portugal\.webp',[\s\S]*?thumbnailPath: '\/images\/titles\/vip\/imperador-portugal\.webp',[\s\S]*?previewPath: '\/images\/titles\/vip\/imperador-portugal\.webp',/,
    `name: '«Campeão Eterno»',
    tier: 4,
    tierName: 'Títulos Imperiais',
    storeSection: 'identities',
    category: 'title',
    rarity: 'Mythic',
    rarityBadge: 'COLECIONADOR MÍTICO',
    prestigeTier: 'MÍTICO',
    profileBannerTag: 'ED. LIMITADA',
    priceEUR: 24.99,
    priceCents: 2499,
    currency: 'EUR',
    isLimited: true,
    limitedUnits: 150,
    stock: 150,
    serialised: true,
    description: 'O título de glória eterna reservado aos maiores campeões da história do Acorda Portugal.',
    visualConcept: 'Placa de ouro cintilante com a inscrição gravada a fogo.',
    animation: 'Letras com reflexo de ouro líquido.',
    effect: 'Exibição destacada na entrada de cada partida.',
    visualEffectsList: ['Ouro líquido nas letras', 'Brilho de campeão'],
    bundleDescription: 'Título mítico animado.',
    assetPath: '/images/titles/vip/campeao-eterno.webp',
    thumbnailPath: '/images/titles/vip/campeao-eterno.webp',
    previewPath: '/images/titles/vip/campeao-eterno.webp',`
  ],
  [
    /name: '«Lenda da Nação»',[\s\S]*?assetPath: '\/images\/titles\/vip\/lenda-nacao\.webp',[\s\S]*?thumbnailPath: '\/images\/titles\/vip\/lenda-nacao\.webp',[\s\S]*?previewPath: '\/images\/titles\/vip\/lenda-nacao\.webp',/,
    `name: '«Cérebro Nacional»',
    tier: 4,
    tierName: 'Títulos Imperiais',
    storeSection: 'identities',
    category: 'title',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 19.99,
    priceCents: 1999,
    currency: 'EUR',
    description: 'A prova inquestionável de um intelecto que domina todos os saberes de Portugal.',
    visualConcept: 'Placa cibernética com pulsos azuis e dourados.',
    animation: 'Circuitos luminosos nas margens do título.',
    effect: 'Destaque no ecrã de resultados.',
    visualEffectsList: ['Pulsos cibernéticos', 'Efeito neon'],
    bundleDescription: 'Título lendário animado.',
    assetPath: '/images/titles/vip/cerebro-nacional.webp',
    thumbnailPath: '/images/titles/vip/cerebro-nacional.webp',
    previewPath: '/images/titles/vip/cerebro-nacional.webp',`
  ],
  [
    /name: '«Cavaleiro de Aljubarrota»',[\s\S]*?assetPath: '\/images\/titles\/vip\/cavaleiro-aljubarrota\.webp',[\s\S]*?thumbnailPath: '\/images\/titles\/vip\/cavaleiro-aljubarrota\.webp',[\s\S]*?previewPath: '\/images\/titles\/vip\/cavaleiro-aljubarrota\.webp',/,
    `name: '«Imperador do Desafio»',
    tier: 4,
    tierName: 'Títulos Imperiais',
    storeSection: 'identities',
    category: 'title',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 16.99,
    priceCents: 1699,
    currency: 'EUR',
    description: 'Soberano absoluto dos confrontos de conhecimento.',
    visualConcept: 'Brasão imperial nobre com letras douradas.',
    animation: 'Brilho volumétrico constante.',
    effect: 'Aura imperial.',
    visualEffectsList: ['Brilho volumétrico', 'Brasão nobre'],
    bundleDescription: 'Título lendário de prestígio.',
    assetPath: '/images/titles/vip/imperador-desafio.webp',
    thumbnailPath: '/images/titles/vip/imperador-desafio.webp',
    previewPath: '/images/titles/vip/imperador-desafio.webp',`
  ],
  [
    /name: '«Mestre dos Saberes»',[\s\S]*?assetPath: '\/images\/titles\/vip\/mestre-saberes\.webp',[\s\S]*?thumbnailPath: '\/images\/titles\/vip\/mestre-saberes\.webp',[\s\S]*?previewPath: '\/images\/titles\/vip\/mestre-saberes\.webp',/,
    `name: '«Lenda de Portugal»',
    tier: 4,
    tierName: 'Títulos Imperiais',
    storeSection: 'identities',
    category: 'title',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 12.99,
    priceCents: 1299,
    currency: 'EUR',
    description: 'Reconhecido em todos os distritos como uma verdadeira lenda viva.',
    visualConcept: 'Placa de bronze nobre polido com as quinas.',
    animation: 'Reflexos de bronze e ouro.',
    effect: 'Efeito luminoso de perfil.',
    visualEffectsList: ['Reflexos de bronze', 'Símbolo das quinas'],
    bundleDescription: 'Título épico de prestígio.',
    assetPath: '/images/titles/vip/lenda-portugal.webp',
    thumbnailPath: '/images/titles/vip/lenda-portugal.webp',
    previewPath: '/images/titles/vip/lenda-portugal.webp',`
  ],
  [
    /name: '«Filho da Lusitânia»',[\s\S]*?assetPath: '\/images\/titles\/vip\/filho-lusitania\.webp',[\s\S]*?thumbnailPath: '\/images\/titles\/vip\/filho-lusitania\.webp',[\s\S]*?previewPath: '\/images\/titles\/vip\/filho-lusitania\.webp',/,
    `name: '«Mestre Lusitano»',
    tier: 4,
    tierName: 'Títulos Imperiais',
    storeSection: 'identities',
    category: 'title',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 9.99,
    priceCents: 999,
    currency: 'EUR',
    description: 'A sabedoria ancestral das raízes lusitanas honrada em cada resposta.',
    visualConcept: 'Letras de esmeralda luminosa e ouro.',
    animation: 'Brilho de esmeralda.',
    effect: 'Aura de mestre.',
    visualEffectsList: ['Brilho de esmeralda', 'Aura de mestre'],
    bundleDescription: 'Título épico lusitano.',
    assetPath: '/images/titles/vip/mestre-lusitano.webp',
    thumbnailPath: '/images/titles/vip/mestre-lusitano.webp',
    previewPath: '/images/titles/vip/mestre-lusitano.webp',`
  ],
  [
    /name: '«Cidadão de Honra»',[\s\S]*?assetPath: '\/images\/titles\/vip\/cidadao-honra\.webp',[\s\S]*?thumbnailPath: '\/images\/titles\/vip\/cidadao-honra\.webp',[\s\S]*?previewPath: '\/images\/titles\/vip\/cidadao-honra\.webp',/,
    `name: '«Senhor do Desafio»',
    tier: 4,
    tierName: 'Títulos Imperiais',
    storeSection: 'identities',
    category: 'title',
    rarity: 'Rare',
    rarityBadge: 'RARO VIP',
    prestigeTier: 'RARO VIP',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 5.99,
    priceCents: 599,
    currency: 'EUR',
    description: 'Título nobre para o jogador dedicado ao Desafio Nacional.',
    visualConcept: 'Placa prateada com quinas a azul e branco.',
    animation: 'Brilho prateado suave.',
    effect: 'Badge prateado no perfil.',
    visualEffectsList: ['Brilho prateado', 'Quinas azuis'],
    bundleDescription: 'Título VIP de entrada.',
    assetPath: '/images/titles/vip/senhor-desafio.webp',
    thumbnailPath: '/images/titles/vip/senhor-desafio.webp',
    previewPath: '/images/titles/vip/senhor-desafio.webp',`
  ],

  // Emotes
  [
    /name: 'A Coroa Desce',[\s\S]*?assetPath: '\/images\/emotes\/vip\/coroa-desce\.webp',[\s\S]*?thumbnailPath: '\/images\/emotes\/vip\/coroa-desce\.webp',[\s\S]*?previewPath: '\/images\/emotes\/vip\/coroa-desce\.webp',/,
    `name: 'Acabou!',
    tier: 5,
    tierName: 'Reações Cinemáticas',
    storeSection: 'reactions',
    category: 'emote',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 12.99,
    priceCents: 1299,
    currency: 'EUR',
    description: 'A sentença final do vencedor: sem palavras, apenas vitória inapelável.',
    visualConcept: 'Símbolo com fogo e impacto de final de jogo.',
    animation: 'Impacto cinemático e estilhaços de vitória.',
    effect: 'Animação e som de vitória no ecrã de duelo.',
    visualEffectsList: ['Impacto cinemático', 'Estilhaços de luz'],
    bundleDescription: 'Emote animado exclusivo.',
    assetPath: '/images/emotes/vip/acabou.webp',
    thumbnailPath: '/images/emotes/vip/acabou.webp',
    previewPath: '/images/emotes/vip/acabou.webp',`
  ],
  [
    /name: 'Orgulho Português',[\s\S]*?assetPath: '\/images\/emotes\/vip\/orgulho-portugues\.webp',[\s\S]*?thumbnailPath: '\/images\/emotes\/vip\/orgulho-portugues\.webp',[\s\S]*?previewPath: '\/images\/emotes\/vip\/orgulho-portugues\.webp',/,
    `name: 'Coroa-te',
    tier: 5,
    tierName: 'Reações Cinemáticas',
    storeSection: 'reactions',
    category: 'emote',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 9.99,
    priceCents: 999,
    currency: 'EUR',
    description: 'A coroa desce sobre o vencedor num gesto de realeza absoluta.',
    visualConcept: 'Coroa de ouro descendo com brilho de vitória.',
    animation: 'Descida suave da coroa com partículas douradas.',
    effect: 'Coroação cinemática no duelo.',
    visualEffectsList: ['Coroação animada', 'Partículas de ouro'],
    bundleDescription: 'Emote animado de coroação.',
    assetPath: '/images/emotes/vip/coroa-te.webp',
    thumbnailPath: '/images/emotes/vip/coroa-te.webp',
    previewPath: '/images/emotes/vip/coroa-te.webp',`
  ],
  [
    /name: 'A Sentença',[\s\S]*?assetPath: '\/images\/emotes\/vip\/a-sentenca\.webp',[\s\S]*?thumbnailPath: '\/images\/emotes\/vip\/a-sentenca\.webp',[\s\S]*?previewPath: '\/images\/emotes\/vip\/a-sentenca\.webp',/,
    `name: 'Mestre Absoluto',
    tier: 5,
    tierName: 'Reações Cinemáticas',
    storeSection: 'reactions',
    category: 'emote',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 8.99,
    priceCents: 899,
    currency: 'EUR',
    description: 'Reconhecimento do estatuto de mestre do saber nacional.',
    visualConcept: 'Insígnia de mestre supremo com raios de sabedoria.',
    animation: 'Raios e halo dourado.',
    effect: 'Pulso de sabedoria.',
    visualEffectsList: ['Raios de sabedoria', 'Halo dourado'],
    bundleDescription: 'Emote épico animado.',
    assetPath: '/images/emotes/vip/mestre-absoluto.webp',
    thumbnailPath: '/images/emotes/vip/mestre-absoluto.webp',
    previewPath: '/images/emotes/vip/mestre-absoluto.webp',`
  ],
  [
    /name: 'Salva ao Vencedor',[\s\S]*?assetPath: '\/images\/emotes\/vip\/salva-vencedor\.webp',[\s\S]*?thumbnailPath: '\/images\/emotes\/vip\/salva-vencedor\.webp',[\s\S]*?previewPath: '\/images\/emotes\/vip\/salva-vencedor\.webp',/,
    `name: 'Nem Acredito!',
    tier: 5,
    tierName: 'Reações Cinemáticas',
    storeSection: 'reactions',
    category: 'emote',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 7.99,
    priceCents: 799,
    currency: 'EUR',
    description: 'Reação de surpresa absoluta perante uma resposta inacreditável.',
    visualConcept: 'Expressão de choque cómico e estupefação intelectual.',
    animation: 'Pulsar e olhos esbugalhados animados.',
    effect: 'Efeito sonoro cómico.',
    visualEffectsList: ['Expressão animada', 'Onda de choque cónica'],
    bundleDescription: 'Emote épico animado.',
    assetPath: '/images/emotes/vip/nem-acredito.webp',
    thumbnailPath: '/images/emotes/vip/nem-acredito.webp',
    previewPath: '/images/emotes/vip/nem-acredito.webp',`
  ],
  [
    /name: '«Nem Acredito!»',[\s\S]*?assetPath: '\/images\/emotes\/vip\/nem-acredito\.webp',[\s\S]*?thumbnailPath: '\/images\/emotes\/vip\/nem-acredito\.webp',[\s\S]*?previewPath: '\/images\/emotes\/vip\/nem-acredito\.webp',/,
    `name: 'Portugal no Topo',
    tier: 5,
    tierName: 'Reações Cinemáticas',
    storeSection: 'reactions',
    category: 'emote',
    rarity: 'Rare',
    rarityBadge: 'RARO VIP',
    prestigeTier: 'RARO VIP',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 6.99,
    priceCents: 699,
    currency: 'EUR',
    description: 'A bandeira de Portugal no topo da classificação com orgulho supremo.',
    visualConcept: 'Bandeira nacional animada hasteada no pódio.',
    animation: 'Bandeira a ondular ao vento com confetis.',
    effect: 'Chuva de confetis verde e rubi.',
    visualEffectsList: ['Bandeira animada', 'Confetis verde e rubi'],
    bundleDescription: 'Emote patriótico de vitória.',
    assetPath: '/images/emotes/vip/portugal-no-topo.webp',
    thumbnailPath: '/images/emotes/vip/portugal-no-topo.webp',
    previewPath: '/images/emotes/vip/portugal-no-topo.webp',`
  ],
  [
    /name: 'Vénia de Cavaleiro',[\s\S]*?assetPath: '\/images\/emotes\/vip\/venia-cavaleiro\.webp',[\s\S]*?thumbnailPath: '\/images\/emotes\/vip\/venia-cavaleiro\.webp',[\s\S]*?previewPath: '\/images\/emotes\/vip\/venia-cavaleiro\.webp',/,
    `name: 'Respeito',
    tier: 5,
    tierName: 'Reações Cinemáticas',
    storeSection: 'reactions',
    category: 'emote',
    rarity: 'Rare',
    rarityBadge: 'RARO VIP',
    prestigeTier: 'RARO VIP',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 5.99,
    priceCents: 599,
    currency: 'EUR',
    description: 'Gesto cavalheiresco de respeito mútuo entre dois grandes adversários.',
    visualConcept: 'Espadas cruzadas e vénia solene.',
    animation: 'Brilho de aço e vénia nobre.',
    effect: 'Som de choque de espadas de honra.',
    visualEffectsList: ['Vénia nobre', 'Choque de espadas'],
    bundleDescription: 'Emote solene de respeito.',
    assetPath: '/images/emotes/vip/respeito.webp',
    thumbnailPath: '/images/emotes/vip/respeito.webp',
    previewPath: '/images/emotes/vip/respeito.webp',`
  ],

  // Tauntpacks
  [
    /name: 'Realeza Absoluta',[\s\S]*?assetPath: '\/images\/tauntpacks\/vip\/realeza-absoluta\.webp',[\s\S]*?thumbnailPath: '\/images\/tauntpacks\/vip\/realeza-absoluta\.webp',[\s\S]*?previewPath: '\/images\/tauntpacks\/vip\/realeza-absoluta\.webp',/,
    `name: 'Realeza Absoluta',
    tier: 6,
    tierName: 'Elite Taunts',
    storeSection: 'taunts',
    category: 'tauntpack',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 9.99,
    priceCents: 999,
    currency: 'EUR',
    description: '6 provocações de alta nobreza pronunciadas com a pose altiva de um soberano.',
    visualConcept: 'Coroa e cetro com estandarte imperial.',
    animation: 'Texto animado com halo dourado.',
    effect: 'Balão de fala estilizado.',
    visualEffectsList: ['Texto dourado', 'Voz de monarca'],
    bundleDescription: 'Pack de 6 provocações reais.',
    assetPath: '/images/taunts/vip/realeza-absoluta/icon.webp',
    thumbnailPath: '/images/taunts/vip/realeza-absoluta/icon.webp',
    previewPath: '/images/taunts/vip/realeza-absoluta/icon.webp',`
  ],
  [
    /name: 'Duelos de Campeões',[\s\S]*?assetPath: '\/images\/tauntpacks\/vip\/duelos-campeoes\.webp',[\s\S]*?thumbnailPath: '\/images\/tauntpacks\/vip\/duelos-campeoes\.webp',[\s\S]*?previewPath: '\/images\/tauntpacks\/vip\/duelos-campeoes\.webp',/,
    `name: 'Guerra dos Campeões',
    tier: 6,
    tierName: 'Elite Taunts',
    storeSection: 'taunts',
    category: 'tauntpack',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 7.99,
    priceCents: 799,
    currency: 'EUR',
    description: '6 frases incisivas para abalar a confiança de qualquer rival em duelo direto.',
    visualConcept: 'Espadas cruzadas com chamas de combate.',
    animation: 'Faíscas e som cortante.',
    effect: 'Balão de fala agressivo.',
    visualEffectsList: ['Faíscas de aço', 'Impacto sonoro'],
    bundleDescription: 'Pack de 6 provocações de guerra.',
    assetPath: '/images/taunts/vip/guerra-campeoes/icon.webp',
    thumbnailPath: '/images/taunts/vip/guerra-campeoes/icon.webp',
    previewPath: '/images/taunts/vip/guerra-campeoes/icon.webp',`
  ],
  [
    /name: 'Lusitano Implacável',[\s\S]*?assetPath: '\/images\/tauntpacks\/vip\/lusitano-implacavel\.webp',[\s\S]*?thumbnailPath: '\/images\/tauntpacks\/vip\/lusitano-implacavel\.webp',[\s\S]*?previewPath: '\/images\/tauntpacks\/vip\/lusitano-implacavel\.webp',/,
    `name: 'Lusitano Implacável',
    tier: 6,
    tierName: 'Elite Taunts',
    storeSection: 'taunts',
    category: 'tauntpack',
    rarity: 'Epic',
    rarityBadge: 'COLEÇÃO EXCLUSIVA',
    prestigeTier: 'ÉPICO',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 7.99,
    priceCents: 799,
    currency: 'EUR',
    description: '6 expressões autênticas da raça lusitana que desarmam o oponente.',
    visualConcept: 'Escudo antigo com relâmpagos.',
    animation: 'Vibração de combate.',
    effect: 'Balão de fala estilizado.',
    visualEffectsList: ['Relâmpagos verdes', 'Som épico'],
    bundleDescription: 'Pack de 6 provocações lusitanas.',
    assetPath: '/images/taunts/vip/lusitano-implacavel/icon.webp',
    thumbnailPath: '/images/taunts/vip/lusitano-implacavel/icon.webp',
    previewPath: '/images/taunts/vip/lusitano-implacavel/icon.webp',`
  ],
  [
    /name: 'O Chefe Final',[\s\S]*?assetPath: '\/images\/tauntpacks\/vip\/o-chefe-final\.webp',[\s\S]*?thumbnailPath: '\/images\/tauntpacks\/vip\/o-chefe-final\.webp',[\s\S]*?previewPath: '\/images\/tauntpacks\/vip\/o-chefe-final\.webp',/,
    `name: 'O Chefe Final',
    tier: 6,
    tierName: 'Elite Taunts',
    storeSection: 'taunts',
    category: 'tauntpack',
    rarity: 'Rare',
    rarityBadge: 'RARO VIP',
    prestigeTier: 'RARO VIP',
    profileBannerTag: 'VIP EXCLUSIVO',
    priceEUR: 5.99,
    priceCents: 599,
    currency: 'EUR',
    description: 'As frases intimidantes de quem já venceu mil duelos e continua invicto.',
    visualConcept: 'Caveira com coroa de campeão.',
    animation: 'Aura negra com olhos vermelhos.',
    effect: 'Som estrondoso.',
    visualEffectsList: ['Aura escura', 'Gongo final'],
    bundleDescription: 'Pack de 6 provocações de chefe final.',
    assetPath: '/images/taunts/vip/final-boss/icon.webp',
    thumbnailPath: '/images/taunts/vip/final-boss/icon.webp',
    previewPath: '/images/taunts/vip/final-boss/icon.webp',`
  ],

  // Bundles
  [
    /name: 'Coroa de Portugal',[\s\S]*?assetPath: '\/bundles\/vip\/coroa-portugal\/banner\.webp',[\s\S]*?thumbnailPath: '\/bundles\/vip\/coroa-portugal\/banner\.webp',[\s\S]*?previewPath: '\/bundles\/vip\/coroa-portugal\/banner\.webp',/,
    `name: 'Campeão Eterno — Conjunto Completo',
    tier: 7,
    tierName: 'Conjuntos Completos',
    storeSection: 'bundles',
    category: 'bundle',
    rarity: 'Mythic',
    rarityBadge: 'COLECIONADOR MÍTICO',
    prestigeTier: 'MÍTICO',
    profileBannerTag: 'ED. LIMITADA',
    priceEUR: 39.99,
    priceCents: 3999,
    currency: 'EUR',
    isLimited: true,
    limitedUnits: 50,
    stock: 50,
    serialised: true,
    description: 'O conjunto mais cobiçado: Avatar Imperador + Trono Supremo + Moldura Coroa + Título Campeão Eterno.',
    visualConcept: 'Showcase completo da linhagem suprema de campeões.',
    animation: 'Transição dourada monumental.',
    effect: 'Desbloqueio de todo o conjunto de campeão.',
    visualEffectsList: ['Todos os efeitos de campeão incluídos'],
    bundleDescription: 'Avatar + Arena + Moldura + Título + Badge de Coleção.',
    assetPath: '/bundles/vip/campeao-eterno/banner.webp',
    thumbnailPath: '/bundles/vip/campeao-eterno/banner.webp',
    previewPath: '/bundles/vip/campeao-eterno/banner.webp',`
  ],
  [
    /name: 'Legado dos Descobrimentos',[\s\S]*?assetPath: '\/bundles\/vip\/legado-descobrimentos\/banner\.webp',[\s\S]*?thumbnailPath: '\/bundles\/vip\/legado-descobrimentos\/banner\.webp',[\s\S]*?previewPath: '\/bundles\/vip\/legado-descobrimentos\/banner\.webp',/,
    `name: 'Coleção Imperial',
    tier: 7,
    tierName: 'Conjuntos Completos',
    storeSection: 'bundles',
    category: 'bundle',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 29.99,
    priceCents: 2999,
    currency: 'EUR',
    description: 'Conjunto completo de prestígio imperial com itens temáticos exclusivos.',
    visualConcept: 'Showcase imperial com cores régias e estandartes.',
    animation: 'Aura imperial e fanfarra.',
    effect: 'Desbloqueio do conjunto imperial.',
    visualEffectsList: ['Efeitos imperiais incluídos'],
    bundleDescription: 'Avatar + Moldura + Título.',
    assetPath: '/bundles/vip/imperial/banner.webp',
    thumbnailPath: '/bundles/vip/imperial/banner.webp',
    previewPath: '/bundles/vip/imperial/banner.webp',`
  ],
  [
    /name: 'Honra Lusitana',[\s\S]*?assetPath: '\/bundles\/vip\/honra-lusitana\/banner\.webp',[\s\S]*?thumbnailPath: '\/bundles\/vip\/honra-lusitana\/banner\.webp',[\s\S]*?previewPath: '\/bundles\/vip\/honra-lusitana\/banner\.webp',/,
    `name: 'Lusitano Supremo',
    tier: 7,
    tierName: 'Conjuntos Completos',
    storeSection: 'bundles',
    category: 'bundle',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 24.99,
    priceCents: 2499,
    currency: 'EUR',
    description: 'Conjunto de guerreiro lusitano com itens patrióticos de topo.',
    visualConcept: 'Armaduras e espadas com relâmpagos verdes.',
    animation: 'Vibração heróica.',
    effect: 'Desbloqueio de guerreiro supremo.',
    visualEffectsList: ['Efeitos lusitanos incluídos'],
    bundleDescription: 'Avatar + Arena + Emote.',
    assetPath: '/bundles/vip/lusitano-supremo/banner.webp',
    thumbnailPath: '/bundles/vip/lusitano-supremo/banner.webp',
    previewPath: '/bundles/vip/lusitano-supremo/banner.webp',`
  ],

  // Ultimate Sets
  [
    /name: 'Portugal Imortal',[\s\S]*?assetPath: '\/ultimate\/vip\/portugal-imortal\/showcase\.webp',[\s\S]*?thumbnailPath: '\/ultimate\/vip\/portugal-imortal\/showcase\.webp',[\s\S]*?previewPath: '\/ultimate\/vip\/portugal-imortal\/showcase\.webp',/,
    `name: 'Identidade de Campeão',
    tier: 8,
    tierName: 'Ultimate Exclusives',
    storeSection: 'ultimate',
    category: 'ultimate',
    rarity: 'Mythic',
    rarityBadge: 'COLECIONADOR MÍTICO',
    prestigeTier: 'MÍTICO',
    profileBannerTag: 'ED. LIMITADA',
    priceEUR: 39.99,
    priceCents: 3999,
    currency: 'EUR',
    isLimited: true,
    limitedUnits: 25,
    stock: 25,
    serialised: true,
    description: 'A peça artística definitiva: uma escultura digital de campeão nacional com holograma em tempo real.',
    visualConcept: 'Monólito de cristal negro e ouro puro com o brasão de Portugal gravado.',
    animation: 'Holograma 3D perpétuo com partículas quânticas.',
    effect: 'Transformação visual completa do perfil do utilizador.',
    visualEffectsList: ['Holograma quântico 3D', 'Perfil personalizado ultra-luxo'],
    bundleDescription: 'Obra de arte digital suprema #XX/25.',
    assetPath: '/ultimate/vip/identidade-campeao/showcase.webp',
    thumbnailPath: '/ultimate/vip/identidade-campeao/showcase.webp',
    previewPath: '/ultimate/vip/identidade-campeao/showcase.webp',`
  ],
  [
    /name: 'O Senhor das Quinas',[\s\S]*?assetPath: '\/ultimate\/vip\/senhor-quinas\/showcase\.webp',[\s\S]*?thumbnailPath: '\/ultimate\/vip\/senhor-quinas\/showcase\.webp',[\s\S]*?previewPath: '\/ultimate\/vip\/senhor-quinas\/showcase\.webp',/,
    `name: 'Legenda Nacional',
    tier: 8,
    tierName: 'Ultimate Exclusives',
    storeSection: 'ultimate',
    category: 'ultimate',
    rarity: 'Mythic',
    rarityBadge: 'COLECIONADOR MÍTICO',
    prestigeTier: 'MÍTICO',
    profileBannerTag: 'ED. LIMITADA',
    priceEUR: 34.99,
    priceCents: 3499,
    currency: 'EUR',
    isLimited: true,
    limitedUnits: 50,
    stock: 50,
    serialised: true,
    description: 'O brasão das Quinas reinterpretado como insígnia máxima da glória nacional.',
    visualConcept: 'Escudo das quinas forjado a ouro com esmeraldas.',
    animation: 'Pulso de luz heróica.',
    effect: 'Brasão destacado em toda a aplicação.',
    visualEffectsList: ['Escudo de ouro tridimensional', 'Partículas de honra'],
    bundleDescription: 'Edição limitada a 50 unidades.',
    assetPath: '/ultimate/vip/legenda-nacional/showcase.webp',
    thumbnailPath: '/ultimate/vip/legenda-nacional/showcase.webp',
    previewPath: '/ultimate/vip/legenda-nacional/showcase.webp',`
  ],
  [
    /name: 'Relíquia da Fundação',[\s\S]*?assetPath: '\/ultimate\/vip\/reliquia-fundacao\/showcase\.webp',[\s\S]*?thumbnailPath: '\/ultimate\/vip\/reliquia-fundacao\/showcase\.webp',[\s\S]*?previewPath: '\/ultimate\/vip\/reliquia-fundacao\/showcase\.webp',/,
    `name: 'Senhor de Portugal',
    tier: 8,
    tierName: 'Ultimate Exclusives',
    storeSection: 'ultimate',
    category: 'ultimate',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 29.99,
    priceCents: 2999,
    currency: 'EUR',
    description: 'A espada e o escudo da fundação de 1143 em versão holográfica de luxo.',
    visualConcept: 'Espada de ferro sagrado com cabo em filigrana e chamas azuis.',
    animation: 'Chamas azuis perpétuas na lâmina.',
    effect: 'Apresentação única em cada partida.',
    visualEffectsList: ['Lâmina com chamas azuis', 'Símbolo da fundação'],
    bundleDescription: 'Relíquia exclusiva de colecionador.',
    assetPath: '/ultimate/vip/senhor-portugal/showcase.webp',
    thumbnailPath: '/ultimate/vip/senhor-portugal/showcase.webp',
    previewPath: '/ultimate/vip/senhor-portugal/showcase.webp',`
  ],
  [
    /name: 'A Alma de Sagres',[\s\S]*?assetPath: '\/ultimate\/vip\/alma-sagres\/showcase\.webp',[\s\S]*?thumbnailPath: '\/ultimate\/vip\/alma-sagres\/showcase\.webp',[\s\S]*?previewPath: '\/ultimate\/vip\/alma-sagres\/showcase\.webp',/,
    `name: 'Trono do Desafio',
    tier: 8,
    tierName: 'Ultimate Exclusives',
    storeSection: 'ultimate',
    category: 'ultimate',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 24.99,
    priceCents: 2499,
    currency: 'EUR',
    description: 'O trono cibernético do conhecimento onde se decide o destino dos desafiantes.',
    visualConcept: 'Estrutura geométrica de mármore e luz com a rosa-dos-ventos holográfica.',
    animation: 'Rosa-dos-ventos holográfica em rotação lenta.',
    effect: 'Aura oceânica e bússola em duelo.',
    visualEffectsList: ['Rosa-dos-ventos animada', 'Luz oceânica'],
    bundleDescription: 'Trono comemorativo do Desafio.',
    assetPath: '/ultimate/vip/trono-desafio/showcase.webp',
    thumbnailPath: '/ultimate/vip/trono-desafio/showcase.webp',
    previewPath: '/ultimate/vip/trono-desafio/showcase.webp',`
  ],
  [
    /name: 'Série Fundador',[\s\S]*?assetPath: '\/ultimate\/vip\/serie-fundador\/showcase\.webp',[\s\S]*?thumbnailPath: '\/ultimate\/vip\/serie-fundador\/showcase\.webp',[\s\S]*?previewPath: '\/ultimate\/vip\/serie-fundador\/showcase\.webp',/,
    `name: 'O Último Desafio',
    tier: 8,
    tierName: 'Ultimate Exclusives',
    storeSection: 'ultimate',
    category: 'ultimate',
    rarity: 'Legendary',
    rarityBadge: 'EDIÇÃO LENDÁRIA',
    prestigeTier: 'LENDÁRIO',
    profileBannerTag: 'COLEÇÃO EXCLUSIVA',
    priceEUR: 19.99,
    priceCents: 1999,
    currency: 'EUR',
    description: 'O troféu dourado definitivo para os jogadores que dominam todos os saberes.',
    visualConcept: 'Troféu monumental em ouro e cristal com chamas comemorativas.',
    animation: 'Chamas comemorativas e reflexos de vitória.',
    effect: 'Exibição de troféu dourado.',
    visualEffectsList: ['Troféu em ouro puro', 'Chamas comemorativas'],
    bundleDescription: 'Item comemorativo exclusivo.',
    assetPath: '/ultimate/vip/ultimo-desafio/showcase.webp',
    thumbnailPath: '/ultimate/vip/ultimo-desafio/showcase.webp',
    previewPath: '/ultimate/vip/ultimo-desafio/showcase.webp',`
  ],
]

let replacedCount = 0
for (const [pattern, replacement] of replacements) {
  if (pattern.test(content)) {
    content = content.replace(pattern, replacement)
    replacedCount++
  } else {
    console.warn(`[WARN] Pattern not matched: ${pattern.toString().slice(0, 40)}...`)
  }
}

fs.writeFileSync(filePath, content, 'utf-8')
console.log(`Updated ${replacedCount} / ${replacements.length} products in vipCatalog.ts!`)
