const fs = require('fs');
const path = require('path');

const rootDir = process.cwd();

function loadJson(relPath) {
  const p = path.join(rootDir, relPath);
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch (e) {
    return null;
  }
}

// Extract MAIN_CATEGORIES and subcategories
// Let's parse MAIN_CATEGORIES from categories-data.ts or read it cleanly
const categoriesTs = fs.readFileSync(path.join(rootDir, 'lib/categories-data.ts'), 'utf8');

// We will construct the exact catalog of 18 official categories and their subcategories
const officialCatalog = [
  {
    id: 'portugal',
    slug: 'portugal',
    name: 'Portugal',
    emoji: '🇵🇹',
    subcategories: [
      { id: 'historia-portugal', name: 'História de Portugal' },
      { id: 'geografia-portugal', name: 'Geografia de Portugal' },
      { id: 'cultura-portuguesa', name: 'Cultura Portuguesa' },
      { id: 'tradicoes', name: 'Tradições' },
      { id: 'monumentos', name: 'Monumentos' },
      { id: 'cidades', name: 'Cidades' },
      { id: 'vilas-aldeias', name: 'Vilas e Aldeias' },
      { id: 'praias', name: 'Praias' },
      { id: 'regioes', name: 'Regiões' },
      { id: 'gastronomia-portuguesa', name: 'Gastronomia Portuguesa' },
      { id: 'personalidades-portuguesas', name: 'Personalidades Portuguesas' },
      { id: 'curiosidades-portugal', name: 'Curiosidades de Portugal' },
    ]
  },
  {
    id: 'atualidade',
    slug: 'atualidade',
    name: 'Atualidade — Portugal Agora',
    emoji: '📰',
    subcategories: [
      { id: 'politica-governo', name: 'Política e Governo' },
      { id: 'assembleia-republica', name: 'Assembleia da República' },
      { id: 'partidos-politicos', name: 'Partidos Políticos' },
      { id: 'lideres-politicos', name: 'Líderes Políticos' },
      { id: 'economia', name: 'Economia' },
      { id: 'salario-minimo', name: 'Salário Mínimo' },
      { id: 'inflacao', name: 'Inflação' },
      { id: 'pib', name: 'PIB' },
      { id: 'emprego', name: 'Emprego' },
      { id: 'habitacao', name: 'Habitação' },
      { id: 'euribor', name: 'Euribor' },
      { id: 'turismo', name: 'Turismo' },
      { id: 'empresas-portuguesas-atual', name: 'Empresas Portuguesas' },
      { id: 'cultura-atual', name: 'Cultura' },
      { id: 'desporto-atual', name: 'Desporto' },
      { id: 'acontecimentos-nacionais', name: 'Acontecimentos Nacionais' },
      { id: 'noticias-verificaveis', name: 'Notícias e Factos Verificáveis' },
    ]
  },
  {
    id: 'portugal-politico',
    slug: 'portugal-politico',
    name: 'Portugal Político',
    emoji: '🏛️',
    subcategories: [
      { id: 'partidos', name: 'Partidos' },
      { id: 'representacao-parlamentar', name: 'Representação Parlamentar' },
      { id: 'lideres', name: 'Líderes' },
      { id: 'historia-politica', name: 'História Política' },
      { id: 'instituicoes', name: 'Instituições' },
      { id: 'constituicao', name: 'Constituição' },
      { id: 'sistema-politico', name: 'Sistema Político' },
      { id: 'eleicoes', name: 'Eleições' },
      { id: 'propostas-politicas', name: 'Propostas Políticas' },
      { id: 'governos', name: 'Governos' },
      { id: 'presidentes-republica', name: 'Presidentes da República' },
      { id: 'primeiros-ministros', name: 'Primeiros-Ministros' },
    ]
  },
  {
    id: 'empresas-portuguesas',
    slug: 'empresas-portuguesas',
    name: 'Empresas Portuguesas',
    emoji: '🏢',
    subcategories: [
      { id: 'empresas', name: 'Empresas' },
      { id: 'marcas', name: 'Marcas' },
      { id: 'fundadores', name: 'Fundadores' },
      { id: 'historia-empresarial', name: 'História Empresarial' },
      { id: 'setores', name: 'Setores' },
      { id: 'produtos', name: 'Produtos' },
      { id: 'servicos', name: 'Serviços' },
      { id: 'empresas-historicas', name: 'Empresas Históricas' },
      { id: 'empresas-atuais', name: 'Empresas Atuais' },
      { id: 'empresas-tecnologicas', name: 'Empresas Tecnológicas' },
      { id: 'empresas-internacionais', name: 'Empresas Internacionais Portuguesas' },
    ]
  },
  {
    id: 'futebol-portugues',
    slug: 'futebol-portugues',
    name: 'Futebol Português',
    emoji: '⚽',
    subcategories: [
      { id: 'clubes', name: 'Clubes' },
      { id: 'jogadores', name: 'Jogadores' },
      { id: 'jogadoras', name: 'Jogadoras' },
      { id: 'estadios', name: 'Estádios' },
      { id: 'competicoes', name: 'Competições' },
      { id: 'liga-portuguesa', name: 'Liga Portuguesa' },
      { id: 'taca-portugal', name: 'Taça de Portugal' },
      { id: 'selecao-nacional', name: 'Seleção Nacional' },
      { id: 'futebol-feminino', name: 'Futebol Feminino' },
      { id: 'treinadores', name: 'Treinadores' },
      { id: 'historia-futebol', name: 'História do Futebol' },
      { id: 'momentos-marcantes', name: 'Momentos Marcantes' },
      { id: 'derbis', name: 'Dérbis & Clássicos' },
      { id: 'recordes-futebol', name: 'Recordes' },
      { id: 'transferencias', name: 'Transferências' },
      { id: 'equipamentos', name: 'Equipamentos' },
      { id: 'futebol-europeu', name: 'Futebol Europeu & Clubes Portugueses' },
    ]
  },
  {
    id: 'desafio-visual',
    slug: 'desafio-visual',
    name: 'Desafio Visual',
    emoji: '👁️',
    subcategories: [
      { id: 'que-lugar-e-este', name: 'Que lugar é este?' },
      { id: 'quem-e-esta-pessoa', name: 'Quem é esta pessoa?' },
      { id: 'bandeiras', name: 'Bandeiras' },
      { id: 'bracoes', name: 'Brasões' },
      { id: 'simbolos', name: 'Símbolos' },
      { id: 'gastronomia-visual', name: 'Gastronomia' },
      { id: 'futebol-visual', name: 'Futebol' },
      { id: 'estadios-visual', name: 'Estádios' },
      { id: 'monumentos-visual', name: 'Monumentos' },
      { id: 'cidades-visual', name: 'Cidades' },
      { id: 'praias-visual', name: 'Praias' },
      { id: 'vilas-aldeias-visual', name: 'Vilas e Aldeias' },
      { id: 'onde-fica-visual', name: 'Onde fica?' },
      { id: 'encontra-detalhe', name: 'Encontra o detalhe' },
      { id: 'fotografias-historicas', name: 'Fotografias Históricas' },
      { id: 'imagens-objetos', name: 'Imagens de Objetos' },
      { id: 'imagens-animais', name: 'Imagens de Animais' },
      { id: 'imagens-natureza', name: 'Imagens de Natureza' },
      { id: 'desafio-visual-maluco', name: 'Desafio Visual Maluco' },
    ]
  },
  {
    id: 'modo-maluco',
    slug: 'modo-maluco',
    name: 'Modo Maluco',
    emoji: '🤪',
    subcategories: [
      { id: 'perguntas-absurdas', name: 'Perguntas Absurdas' },
      { id: 'perguntas-inesperadas', name: 'Perguntas Inesperadas' },
      { id: 'humor-maluco', name: 'Humor & Rir' },
      { id: 'cultura-popular-maluca', name: 'Cultura Popular Insólita' },
      { id: 'regras-aleatorias', name: 'Regras Aleatórias' },
      { id: 'desafios-rapidos', name: 'Desafios Rápidos' },
      { id: 'efeitos-especiais', name: 'Efeitos Especiais' },
      { id: 'modificadores-jogo', name: 'Modificadores de Jogo' },
      { id: 'perguntas-logica-diferente', name: 'Perguntas com Lógica Diferente' },
      { id: 'modo-caos', name: 'Modo Caos' },
    ]
  },
  {
    id: 'historia',
    slug: 'historia',
    name: 'História',
    emoji: '🏺',
    subcategories: [
      { id: 'historia-de-portugal', name: 'História de Portugal' },
      { id: 'historia-mundial', name: 'História Mundial' },
      { id: 'reis-e-rainhas', name: 'Reis e Rainhas' },
      { id: 'descobrimentos', name: 'Descobrimentos & Navegações' },
      { id: 'batalhas', name: 'Batalhas & Conflitos' },
      { id: 'imperios', name: 'Impérios Históricos' },
      { id: 'revolucoes', name: 'Revoluções' },
      { id: 'republica', name: 'Implantação da República' },
      { id: 'estado-novo', name: 'Estado Novo' },
      { id: 'vinte-cinco-abril', name: '25 de Abril & Cravos' },
      { id: 'personalidades-historicas', name: 'Personalidades Históricas' },
      { id: 'civilizacoes-antigas', name: 'Civilizações Antigas' },
      { id: 'idade-media', name: 'Idade Média' },
      { id: 'idade-moderna', name: 'Idade Moderna' },
      { id: 'historia-contemporanea', name: 'História Contemporânea' },
    ]
  },
  {
    id: 'geografia',
    slug: 'geografia',
    name: 'Geografia',
    emoji: '🌍',
    subcategories: [
      { id: 'geografia-portugal', name: 'Geografia de Portugal' },
      { id: 'geografia-europa', name: 'Europa' },
      { id: 'geografia-mundo', name: 'Mundo' },
      { id: 'paises', name: 'Países' },
      { id: 'capitais', name: 'Capitais' },
      { id: 'cidades-mundo', name: 'Grandes Cidades' },
      { id: 'rios', name: 'Rios' },
      { id: 'montanhas', name: 'Montanhas & Serras' },
      { id: 'ilhas', name: 'Ilhas & Arquipélagos' },
      { id: 'oceanos-mares', name: 'Oceanos & Mares' },
      { id: 'fronteiras', name: 'Fronteiras & Tratados' },
      { id: 'regioes-mundo', name: 'Regiões' },
      { id: 'mapas', name: 'Mapas & Cartografia' },
      { id: 'localizacao-geografica', name: 'Localização Geográfica' },
    ]
  },
  {
    id: 'ciencia-tecnologia',
    slug: 'ciencia-tecnologia',
    name: 'Ciência e Tecnologia',
    emoji: '🔬',
    subcategories: [
      { id: 'ciencia-geral', name: 'Ciência Geral' },
      { id: 'fisica', name: 'Física' },
      { id: 'quimica', name: 'Química' },
      { id: 'biologia', name: 'Biologia' },
      { id: 'astronomia-espaco', name: 'Astronomia & Espaço' },
      { id: 'corpo-humano', name: 'Corpo Humano' },
      { id: 'animais-natureza', name: 'Animais & Natureza' },
      { id: 'tecnologia-geral', name: 'Tecnologia' },
      { id: 'informatica-internet', name: 'Informática & Internet' },
      { id: 'inteligencia-artificial', name: 'Inteligência Artificial' },
      { id: 'invencoes', name: 'Invenções' },
      { id: 'descobertas-cientificas', name: 'Descobertas Científicas' },
    ]
  },
  {
    id: 'cultura',
    slug: 'cultura',
    name: 'Cultura',
    emoji: '🎭',
    subcategories: [
      { id: 'cultura-portuguesa-geral', name: 'Cultura Portuguesa' },
      { id: 'cultura-mundial', name: 'Cultura Mundial' },
      { id: 'arte-pintura-escultura', name: 'Arte, Pintura e Escultura' },
      { id: 'literatura', name: 'Literatura' },
      { id: 'teatro', name: 'Teatro' },
      { id: 'fotografia', name: 'Fotografia' },
      { id: 'musica-cultura', name: 'Música Erudita & Tradicional' },
      { id: 'cinema-cultura', name: 'Cinema de Autor' },
      { id: 'televisao-cultura', name: 'Televisão Cultural' },
      { id: 'cultura-popular', name: 'Cultura Popular' },
      { id: 'tradicoes-folclore', name: 'Tradições & Folclore' },
    ]
  },
  {
    id: 'gastronomia',
    slug: 'gastronomia',
    name: 'Gastronomia',
    emoji: '🍲',
    subcategories: [
      { id: 'gastronomia-portuguesa-geral', name: 'Gastronomia Portuguesa' },
      { id: 'pratos-portugueses', name: 'Pratos Típicos Portugueses' },
      { id: 'doces-portugueses', name: 'Doces & Sobremesas Tradicionais' },
      { id: 'bebidas-vinhos', name: 'Bebidas & Vinhos de Portugal' },
      { id: 'ingredientes', name: 'Ingredientes & Especiarias' },
      { id: 'receitas-tradicionais', name: 'Receitas Tradicionais' },
      { id: 'regioes-gastronomicas', name: 'Regiões Gastronómicas' },
      { id: 'gastronomia-mundial', name: 'Gastronomia Mundial' },
      { id: 'comida-internacional', name: 'Comida Internacional' },
      { id: 'identificacao-visual-pratos', name: 'Identificação Visual de Pratos' },
      { id: 'curiosidades-gastronomicas', name: 'Curiosidades Gastronómicas' },
    ]
  },
  {
    id: 'desporto',
    slug: 'desporto',
    name: 'Desporto',
    emoji: '🏆',
    subcategories: [
      { id: 'futebol-modalidade', name: 'Futebol Geral' },
      { id: 'atletismo', name: 'Atletismo & Maratonas' },
      { id: 'tenis', name: 'Ténis' },
      { id: 'ciclismo', name: 'Ciclismo & Volta a Portugal' },
      { id: 'basquetebol', name: 'Basquetebol & NBA' },
      { id: 'formula-1', name: 'Fórmula 1 & Motores' },
      { id: 'surf', name: 'Surf & Ondas Gigantes' },
      { id: 'natacao', name: 'Natação & Desportos Aquáticos' },
      { id: 'jogos-olimpicos', name: 'Jogos Olímpicos' },
      { id: 'artes-marciais', name: 'Artes Marciais & Judo' },
      { id: 'motociclismo', name: 'Motociclismo & MotoGP' },
      { id: 'desporto-portugues', name: 'Desporto Português' },
      { id: 'desporto-internacional', name: 'Desporto Internacional' },
      { id: 'recordes-desportivos', name: 'Recordes Mundiais' },
      { id: 'competicoes-desportivas', name: 'Grandes Competições' },
    ]
  },
  {
    id: 'humor',
    slug: 'humor',
    name: 'Humor',
    emoji: '😂',
    subcategories: [
      { id: 'humor-portugues', name: 'Humor Português' },
      { id: 'expressoes-portuguesas', name: 'Expressões Populares Portuguesas' },
      { id: 'memes', name: 'Memes & Internet' },
      { id: 'cultura-popular-humor', name: 'Comédia na TV & Cinema' },
      { id: 'situacoes-quotidiano', name: 'Situações do Quotidiano' },
      { id: 'perguntas-engracadas', name: 'Perguntas Engraçadas' },
      { id: 'curiosidades-engracadas', name: 'Curiosidades Hilariantes' },
      { id: 'modo-maluco-humor', name: 'Humor Absurdo' },
    ]
  },
  {
    id: 'musica',
    slug: 'musica',
    name: 'Música',
    emoji: '🎵',
    subcategories: [
      { id: 'musica-portuguesa-geral', name: 'Música Portuguesa' },
      { id: 'fado', name: 'Fado & Guitarra Portuguesa' },
      { id: 'musica-popular-portuguesa', name: 'Música Popular & Pimba' },
      { id: 'artistas-portugueses', name: 'Artistas & Cantores Portugueses' },
      { id: 'bandas-portuguesas', name: 'Bandas Portuguesas' },
      { id: 'musica-internacional', name: 'Música Internacional' },
      { id: 'artistas-internacionais', name: 'Artistas Internacionais' },
      { id: 'bandas-internacionais', name: 'Bandas Internacionais Lendárias' },
      { id: 'cancoes', name: 'Grandes Canções' },
      { id: 'albuns', name: 'Álbuns Históricos' },
      { id: 'instrumentos', name: 'Instrumentos Musicais' },
      { id: 'historia-musica', name: 'História da Música' },
      { id: 'festivais-musica', name: 'Festivais de Música' },
    ]
  },
  {
    id: 'cinema-tv',
    slug: 'cinema-tv',
    name: 'Cinema e Televisão',
    emoji: '🎬',
    subcategories: [
      { id: 'filmes', name: 'Grandes Filmes' },
      { id: 'series', name: 'Séries Marcantes' },
      { id: 'atores-atrizes', name: 'Atores e Atrizes' },
      { id: 'personagens', name: 'Personagens Inesquecíveis' },
      { id: 'realizadores', name: 'Realizadores' },
      { id: 'cinema-portugues', name: 'Cinema Português' },
      { id: 'televisao-portuguesa', name: 'Televisão Portuguesa' },
      { id: 'programas-televisao', name: 'Programas de Televisão Clássicos' },
      { id: 'streaming', name: 'Streaming & Novas Séries' },
      { id: 'cultura-pop', name: 'Cultura Pop & Geek' },
      { id: 'filmes-classicos', name: 'Filmes Clássicos' },
    ]
  },
  {
    id: 'personalidades',
    slug: 'personalidades',
    name: 'Personalidades',
    emoji: '👤',
    subcategories: [
      { id: 'figuras-historicas', name: 'Figuras Históricas' },
      { id: 'politicos', name: 'Políticos & Estadistas' },
      { id: 'artistas', name: 'Artistas & Pintores' },
      { id: 'atletas', name: 'Atletas Lendários' },
      { id: 'cientistas', name: 'Cientistas & Pensadores' },
      { id: 'empresarios', name: 'Empresários & Empreendedores' },
      { id: 'escritores', name: 'Escritores & Poetas' },
      { id: 'musicos', name: 'Músicos & Compositores' },
      { id: 'atores', name: 'Atores & Intérpretes' },
      { id: 'criadores', name: 'Criadores & Inovadores' },
      { id: 'personalidades-internacionais', name: 'Personalidades Internacionais' },
      { id: 'personalidades-portuguesas', name: 'Personalidades Portuguesas' },
    ]
  },
  {
    id: 'mundo',
    slug: 'mundo',
    name: 'Mundo',
    emoji: '🌐',
    subcategories: [
      { id: 'paises-mundo', name: 'Países & Continentes' },
      { id: 'capitais-mundo', name: 'Capitais do Mundo' },
      { id: 'historia-mundial-geral', name: 'História Mundial' },
      { id: 'geografia-mundial-geral', name: 'Geografia Mundial' },
      { id: 'cultura-mundo', name: 'Culturas & Costumes Globais' },
      { id: 'ciencia-tecnologia-mundo', name: 'Ciência & Tecnologia no Mundo' },
      { id: 'economia-mundo', name: 'Economia Global' },
      { id: 'desporto-mundo', name: 'Desporto Mundial' },
      { id: 'musica-mundo', name: 'Música do Mundo' },
      { id: 'cinema-mundo', name: 'Cinema Internacional' },
      { id: 'personalidades-mundo', name: 'Personalidades do Mundo' },
      { id: 'curiosidades-mundo', name: 'Curiosidades Mundiais' },
      { id: 'atualidade-internacional', name: 'Atualidade Internacional' },
    ]
  },
];

console.log('Official Catalog loaded:', officialCatalog.length, 'categories,', officialCatalog.reduce((s, c) => s + c.subcategories.length, 0), 'subcategories');
